import {test,expect} from '@playwright/test';
import {detailMembers} from '../src/inspection-catalog.js';
test('body panels share vehicle surfaces and expose hinges, torque rods, latches and retainers',async({page})=>{
 test.setTimeout(840000);page.setDefaultTimeout(45000);const errors=[],images=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.resourceType()==='image')images.push(r.url());});
 await page.goto('/');await page.waitForFunction(()=>window.__fiero&&document.querySelector('canvas').dataset.ready==='true',null,{timeout:180000});await expect(page.locator('#loading')).toHaveCount(0);
 const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const capture=async name=>{await settle();await page.screenshot({path:`artifacts/${name}.png`});console.log('Captured '+name);};
 const scope=async id=>{await page.locator(`#systems [data-assembly="${id}"]`).click();await expect(page.locator('canvas')).toHaveAttribute('data-assembly',id);};const reset=async()=>page.getByRole('button',{name:'Reset view',exact:true}).click();
 await capture('vehicle-after-body-hardware');await page.locator('#systems [data-system="body"]').click();await page.locator('.part-button[data-part="hood"]').click();await page.getByRole('button',{name:'Explode this assembly',exact:true}).click();await reset();await capture('body-hood-assembled');
 expect((await page.evaluate(()=>window.__fiero.getVisibleParts())).sort()).toEqual(detailMembers('body-hood').map(p=>p.id).sort());await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('body-hood-exploded');await page.locator('.part-button[data-part="bd-hood-stay"]').click();await expect(page.locator('#inspector-content')).toContainText('sliding');await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();await capture('body-hood-stay');
 await scope('body-decklid');await reset();await capture('body-decklid-assembled');await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('body-decklid-exploded');await page.locator('.part-button[data-part="bd-deck-left-rod"]').click();await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();expect(await page.evaluate(()=>window.__fiero.getVisibleParts())).toEqual(['bd-deck-left-rod']);
 await scope('body-door-left');await reset();await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('body-driver-door-exploded');await page.locator('.part-button[data-part="bd-door-left-lower-body"]').click();await page.getByRole('button',{name:'Focus part',exact:true}).click();await capture('body-driver-hinge');
 await scope('body-side-panels');await reset();await capture('body-rocker-covers');await scope('body-front-panels');await reset();await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('body-front-panels-exploded');await scope('body-rear-panels');await reset();await capture('body-rear-panels');
 await scope('body-rear-clip');await reset();await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('body-rear-clip-exploded');await scope('body-roof');await reset();await page.getByRole('button',{name:'Configure',exact:true}).click();await page.getByRole('button',{name:'White paint',exact:true}).click();await page.locator('#config-roof').selectOption('glass');const glazed=await page.evaluate(()=>window.__fiero.getModelStats().triangles);await page.locator('#config-roof').selectOption('removed');expect(await page.evaluate(()=>window.__fiero.getModelStats().triangles)).toBeLessThan(glazed);await page.locator('[data-tab="component"]').click();await capture('body-roof-open-white');
 await page.getByRole('button',{name:'Configure',exact:true}).click();await page.getByRole('button',{name:'Reset preview choices',exact:true}).click();await page.locator('[data-tab="component"]').click();await scope('body-system');await reset();await capture('body-complete-panels');
 await scope('fuel-system');await scope('fuel-tank');await reset();await capture('fuel-tank-sidewall-refined');await page.getByRole('button',{name:'Back to vehicle',exact:false}).click();await expect(page.locator('canvas')).toHaveAttribute('data-selected','hood');await reset();await capture('body-vehicle-return');
 await page.setViewportSize({width:390,height:700});await page.getByRole('button',{name:'Open assemblies',exact:true}).click();await page.getByRole('searchbox').fill('Driver lower hinge pin');await page.locator('.part-button[data-part="bd-door-left-lower-pin"]').click();await expect(page.locator('canvas')).toHaveAttribute('data-assembly','body-door-left');await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();await capture('body-hardware-mobile');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);expect(images).toEqual([]);
});
