import {test,expect} from '@playwright/test';
import {detailMembers} from '../src/inspection-catalog.js';

test('1985 brakes expose distinct corners, hydraulic internals and parking controls',async({page})=>{
 test.setTimeout(720000);
 const errors=[],images=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.resourceType()==='image')images.push(r.url());});
 await page.goto('/');await page.waitForFunction(()=>window.__fiero);
 const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
 const capture=async name=>{await settle();await page.screenshot({path:`artifacts/${name}.png`});console.log('Captured '+name);};
 const scope=async id=>{await page.locator(`#systems [data-assembly="${id}"]`).click();await expect(page.locator('canvas')).toHaveAttribute('data-assembly',id);};
 const reset=async()=>page.getByRole('button',{name:'Reset view',exact:true}).click();
 await page.locator('#systems [data-system="brakes"]').click();await page.locator('.part-button[data-part="calipers"]').click();await page.getByRole('button',{name:'Explode this assembly',exact:true}).click();
 await expect(page.locator('canvas')).toHaveAttribute('data-assembly','braking-system');await expect(page.locator('.part-button')).toHaveCount(detailMembers('braking-system').length);
 await expect(page.locator('#explode')).toHaveAccessibleName('Brakes exploded view');await reset();await capture('brakes-complete-circuit');
 await scope('brake-front');await scope('brake-fl');await scope('brake-fl-caliper');await reset();
 expect((await page.evaluate(()=>window.__fiero.getVisibleParts())).sort()).toEqual(detailMembers('brake-fl-caliper').map(p=>p.id).sort());await capture('brakes-front-caliper-assembled');
 const before=await page.evaluate(()=>window.__fiero.getPartBounds('br-fl-piston'));
 await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await settle();
 const after=await page.evaluate(()=>window.__fiero.getPartBounds('br-fl-piston'));expect(after.min[0]-before.min[0]).toBeCloseTo(-.18,3);await capture('brakes-front-caliper-exploded');
 await scope('brake-fl-hub');await reset();await page.locator('.part-button[data-part="br-fl-rotor"]').click();
 await expect(page.locator('.part-service-reference')).toContainText('10.922 mm');await expect(page.locator('.part-service-reference')).toContainText('not machining or discard limits');
 await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('brakes-front-hub-exploded');
 await scope('brake-rear');await scope('brake-rl');await scope('brake-rl-caliper');await reset();await capture('brakes-rear-caliper-assembled');
 await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('brakes-rear-caliper-exploded');
 await page.locator('.part-button[data-part="br-rl-actuator"]').click();await expect(page.locator('#inspector-content')).toContainText('1985 Pontiac service');await expect(page.locator('#inspector-content')).toContainText('callout 19');
 await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();expect(await page.evaluate(()=>window.__fiero.getVisibleParts())).toEqual(['br-rl-actuator']);
 await scope('brake-rl-hub');await reset();await page.locator('.part-button[data-part="br-rl-rotor"]').click();await expect(page.locator('.part-service-reference')).toContainText('12.700 mm');
 await scope('brake-hydraulics');await scope('brake-master');await reset();await capture('brakes-master-assembled');await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('brakes-master-exploded');
 await scope('brake-booster');await reset();await capture('brakes-booster-assembled');await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('brakes-booster-exploded');
 await scope('brake-lines');await reset();await capture('brakes-lines');
 await scope('brake-parking');await reset();await capture('brakes-parking-cables');
 await page.locator('.part-button[data-part="br-park-lever"]').click();await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();await capture('brakes-parking-lever');
 const lever=await page.evaluate(()=>window.__fiero.getPartBounds('br-park-lever'));expect(lever.max[0]).toBeLessThan(0);
 await scope('engine');await expect(page.locator('.part-button')).toHaveCount(detailMembers('engine').length);
 await page.getByRole('button',{name:'Back to vehicle',exact:false}).click();await expect(page.locator('canvas')).toHaveAttribute('data-selected','calipers');expect(await page.evaluate(()=>window.__fiero.getState().system)).toBe('brakes');
 await reset();await capture('vehicle-after-brakes');
 await page.setViewportSize({width:390,height:700});await page.getByRole('button',{name:'Open assemblies',exact:true}).click();await page.getByRole('searchbox').fill('right rear parking-brake actuator');
 await page.locator('.part-button[data-part="br-rr-actuator"]').click();await expect(page.locator('canvas')).toHaveAttribute('data-assembly','brake-rr-caliper');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('.sidebar')).not.toHaveClass(/mobile-open/);
 await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();await settle();await page.screenshot({path:'artifacts/brakes-mobile.png',fullPage:true});
 expect(errors).toEqual([]);expect(images).toEqual([]);
});
