import {waitForViewer,evaluateViewer} from './viewer-ready.js';
import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
test('compact spare explorer separates the 1985 wheel, valve, jack construction and stowage hardware',async({page})=>{
 test.setTimeout(540000);page.setDefaultTimeout(60000);page.setDefaultNavigationTimeout(240000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const output='artifacts/completion-spare-browser/'+new Date().toISOString().replace(/[:.]/g,'-');await mkdir(output,{recursive:true});
 const capture=async name=>{await evaluateViewer(page,()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await waitForViewer(page);await page.screenshot({path:`${output}/${name}.png`});console.log(`Captured ${output}/${name}.png`);};
 const scope=async id=>{await page.locator(`#systems [data-assembly="${id}"]`).click();await page.getByRole('button',{name:'Reset view',exact:true}).click();await waitForViewer(page);await expect(page.locator('canvas')).toHaveAttribute('data-assembly',id);};
 await page.goto('/');await page.waitForFunction(()=>document.querySelector('canvas')?.dataset.ready==='true',null,{timeout:240000});
 await page.getByRole('searchbox').fill('Compact spare');await page.locator('.part-button[data-part="spare-wheel"]').click();await page.getByRole('button',{name:'Explode this assembly',exact:true}).click();await page.getByRole('button',{name:'Reset view',exact:true}).click();
 expect(await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).toHaveLength(25);await capture('spare-stowed');
 await scope('spare-wheel');expect(await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).toHaveLength(6);await page.locator('.part-button[data-part="sp-tire"]').click();await expect(page.locator('#inspector-content')).toContainText('415 kPa / 60 psi');await expect(page.locator('#inspector-content')).toContainText('15 × 4');await capture('wheel-valve');
 await page.locator('.part-button[data-part="sp-rim"]').click();await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();expect(await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).toEqual(['sp-rim']);await expect(page.locator('#inspector-content')).toContainText('9590503');await capture('compact-steel-wheel-openings');
 await scope('spare-jack');expect(await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).toHaveLength(10);await capture('jack-stored');await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('jack-construction');
 await page.locator('.part-button[data-part="sp-jack-head"]').click();await expect(page.locator('#inspector-content')).toContainText('10030932');await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();await capture('jack-head-groove');
 await scope('spare-stowage');expect(await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).toHaveLength(9);await capture('retainers-wrench');await page.locator('.part-button[data-part="sp-wrench"]').click();await expect(page.locator('#inspector-content')).toContainText('19.56 mm');
 await page.getByRole('button',{name:'Back to vehicle',exact:false}).click();await waitForViewer(page);await expect(page.locator('canvas')).toHaveAttribute('data-selected','spare-wheel');
 await page.setViewportSize({width:390,height:700});await page.getByRole('button',{name:'Open assemblies',exact:true}).click();await page.getByRole('searchbox').fill('Valve dust cap');await page.locator('.part-button[data-part="sp-valve-cap"]').click();await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();expect(await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).toEqual(['sp-valve-cap']);await capture('mobile-valve-cap');expect(await evaluateViewer(page,()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
