import {waitForViewer,evaluateViewer} from './viewer-ready.js';
import {test,expect} from '@playwright/test';
import {wiperParts} from '../src/wiper-catalog.js';
test('wipers expose standard and pulse motor alternatives, washer pump, isolation and mobile return',async({page})=>{
 test.setTimeout(720000);page.setDefaultTimeout(60000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.waitForFunction(()=>window.__fiero&&document.querySelector('canvas').dataset.ready==='true',null,{timeout:240000});
 await page.getByRole('searchbox').fill('Wiper motor');
 await page.locator('.part-button[data-part="wiper-mechanism"]').click();
 await page.getByRole('button',{name:'Explode this assembly',exact:true}).click();
 await waitForViewer(page);await expect(page.locator('canvas')).toHaveAttribute('data-assembly','wiper-system');
 await page.getByRole('button',{name:'Reset view',exact:true}).click();
 expect(await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).toContain('ww-motor-armature');
 expect(await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).not.toContain('ww-pulse-board');
 await page.locator('#systems [data-assembly="wiper-motor"]').click();
 await page.getByRole('button',{name:'Reset view',exact:true}).click();
 await waitForViewer(page);await page.screenshot({path:'artifacts/completion-wiper-standard.png'});
 await page.getByRole('button',{name:'Explode assembly',exact:true}).click();
 await waitForViewer(page);await page.screenshot({path:'artifacts/completion-wiper-standard-exploded.png'});
 await page.locator('.part-button[data-part="ww-motor-armature"]').click();
 await page.getByRole('button',{name:'Isolate',exact:true}).click();
 expect(await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).toEqual(['ww-motor-armature']);
 await page.getByRole('button',{name:'Configure',exact:true}).click();
 await page.locator('[data-config="delayWipers"]').check();
 await page.getByRole('button',{name:'Reset view',exact:true}).click();
 const pulse=await evaluateViewer(page,()=>window.__fiero.getVisibleParts());
 expect(pulse).toContain('ww-pulse-board');expect(pulse).not.toContain('ww-motor-armature');
 await waitForViewer(page);await page.screenshot({path:'artifacts/completion-wiper-pulse.png'});
 await page.locator('#systems [data-assembly="wiper-system"]').click();
 await page.locator('#systems [data-assembly="wiper-washer"]').click();
 await page.getByRole('button',{name:'Reset view',exact:true}).click();
 expect((await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).sort()).toEqual(wiperParts.filter(p=>p.section==='wiper-washer').map(p=>p.id).sort());
 await waitForViewer(page);await page.screenshot({path:'artifacts/completion-washer.png'});
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Open assemblies'}).click();
 await page.getByRole('searchbox').fill('Bottom-mounted washer pump');
 await page.locator('.part-button[data-part="ww-washer-pump"]').click();
 await page.getByRole('button',{name:'Isolate',exact:true}).click();
 await page.getByRole('button',{name:'Focus part',exact:true}).click();
 expect(await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).toEqual(['ww-washer-pump']);
 expect(await evaluateViewer(page,()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await waitForViewer(page);await page.screenshot({path:'artifacts/completion-washer-mobile.png'});
 await page.getByRole('button',{name:'Back to vehicle',exact:false}).click();
 await waitForViewer(page);await expect(page.locator('canvas')).toHaveAttribute('data-selected','wiper-mechanism');
 expect(errors).toEqual([]);
});
