import {waitForViewer,evaluateViewer} from './viewer-ready.js';
import {test,expect} from '@playwright/test';
test('new exterior opening trim stays installed with windows down and is independently inspectable',async({page})=>{
 test.setTimeout(360000);page.setDefaultTimeout(60000);page.setDefaultNavigationTimeout(240000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.waitForFunction(()=>window.__fiero&&document.querySelector('canvas').dataset.ready==='true');
 await page.getByRole('button',{name:'Configure',exact:true}).click();await page.getByLabel('Side windows',{exact:true}).selectOption('open');
 const trim=['a-pillar-seal','upper-window-seal','b-pillar-seal','windshield-belt-filler','backlight-filler'].flatMap(prefix=>['left','right'].map(side=>prefix+'-'+side));
 const bounds=await evaluateViewer(page,ids=>Object.fromEntries(ids.map(id=>[id,window.__fiero.getPartBounds(id)])),[...trim,'door-glass-left','door-glass-right']);
 for(const id of trim){expect(bounds[id],id).not.toBeNull();expect(bounds[id].max.every(Number.isFinite),id).toBe(true);}expect(bounds['door-glass-left']).toBeNull();expect(bounds['door-glass-right']).toBeNull();
 await page.locator('[data-view="side"]').click();await waitForViewer(page);await page.locator('#viewport').screenshot({path:'artifacts/exterior-r10-windows-open.png'});
 await page.getByRole('searchbox').fill('Driver upper window seal');await page.locator('.part-button[data-part="upper-window-seal-left"]').click();await page.getByRole('button',{name:'Explode this assembly',exact:true}).click();await waitForViewer(page);await expect(page.locator('canvas')).toHaveAttribute('data-assembly','body-roof');
 await page.locator('.part-button[data-part="bd-skin-upper-window-seal-left"]').click();await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();expect(await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).toEqual(['bd-skin-upper-window-seal-left']);await waitForViewer(page);await page.locator('#viewport').screenshot({path:'artifacts/exterior-r10-window-retainer.png'});
 await page.getByRole('button',{name:'Back to vehicle',exact:false}).click();await page.setViewportSize({width:390,height:740});await page.getByRole('button',{name:'Open assemblies',exact:true}).click();await page.getByRole('searchbox').fill('Passenger windshield belt corner filler');await page.locator('.part-button[data-part="windshield-belt-filler-right"]').click();await page.getByRole('button',{name:'Explode this assembly',exact:true}).click();await waitForViewer(page);await expect(page.locator('canvas')).toHaveAttribute('data-assembly','body-glazing');expect(await evaluateViewer(page,()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);await waitForViewer(page);await page.screenshot({path:'artifacts/exterior-r10-mobile-filler.png',fullPage:true});
});
