import {test,expect} from '@playwright/test';
import {headlightParts} from '../src/headlight-catalog.js';
import {detailMembers,detailSectionById} from '../src/inspection-catalog.js';
import {remainingWork} from '../src/remaining-work.js';
test('1985 headlights expose both sides, early motor internals, independent covers and a complete remaining-work list',async({page})=>{
 test.setTimeout(840000);page.setDefaultTimeout(60000);const errors=[],images=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.resourceType()==='image')images.push(r.url());});
 await page.goto('/');await page.waitForFunction(()=>window.__fiero&&document.querySelector('canvas').dataset.ready==='true',null,{timeout:180000});
 const capture=async name=>{await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot({path:`artifacts/${name}.png`});console.log('Captured '+name);};
 const reset=()=>page.getByRole('button',{name:'Reset view',exact:true}).click();const scope=async id=>{if(!await page.locator(`#systems [data-assembly="${id}"]`).count()){const parent=detailSectionById.get(id)?.parent;if(parent)await scope(parent);}await page.locator(`#systems [data-assembly="${id}"]`).click();await expect(page.locator('canvas')).toHaveAttribute('data-assembly',id);};
 await capture('headlights-vehicle-closed');const closed=await page.evaluate(()=>window.__fiero.getPartBounds('headlights'));
 await page.getByRole('button',{name:'Reference library',exact:true}).click();await page.getByRole('button',{name:'Remaining model & manual work',exact:true}).click();await expect(page.locator('#modal')).toBeVisible();await expect(page.locator('#modal .source-card')).toHaveCount(remainingWork.length);await expect(page.locator('#modal .source-card').first()).toContainText('1. Headlights');await expect(page.locator('#modal li')).toHaveCount(73);await capture('remaining-work-checklist');await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.locator('#systems [data-system="electrical"]').click();await page.locator('.part-button[data-part="headlights"]').click();await page.getByRole('button',{name:'Explode this assembly',exact:true}).click();await reset();
 expect((await page.evaluate(()=>window.__fiero.getVisibleParts())).sort()).toEqual(headlightParts.map(p=>p.id).sort());
 await page.getByRole('button',{name:'Raise headlights',exact:true}).click();await capture('headlights-pair-raised');
 for(const side of ['left','right']){
  await scope('headlight-'+side);await reset();await capture('headlight-'+side+'-assembled');
  const lens=await page.evaluate(id=>window.__fiero.getPartBounds(id),'hl-'+side+'-lens');expect(side==='left'?lens.max[0]<0:lens.min[0]>0).toBe(true);
  await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('headlight-'+side+'-exploded');
 }
 await scope('headlight-left-lamp');await reset();await capture('headlight-lamp-assembled');await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('headlight-lamp-exploded');
 await page.locator('.part-button[data-part="hl-left-aim-spring"]').click();await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();await expect(page.locator('#inspector-content')).toContainText('bottom-corner');await expect(page.locator('#inspector-content a').first()).toHaveAttribute('href',/#page=69$/);await capture('headlight-aim-spring');
 await scope('headlight-left-motor');await reset();await capture('headlight-motor-assembled');await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('headlight-motor-exploded');
 expect((await page.evaluate(()=>window.__fiero.getVisibleParts())).sort()).toEqual(detailMembers('headlight-left-motor').map(p=>p.id).sort());
 await page.locator('.part-button[data-part="hl-left-output-gear"]').click();await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();await capture('headlight-plastic-output-gear');
 await scope('headlight-left-door');await reset();await capture('headlight-cover-raised');await page.getByRole('button',{name:'Lower headlights',exact:true}).click();await capture('headlight-cover-closed');await scope('headlight-left');await reset();await capture('headlight-closed-mechanism');const low=await page.evaluate(()=>window.__fiero.getPartBounds('hl-left-lens'));await page.getByRole('button',{name:'Raise headlights',exact:true}).click();const high=await page.evaluate(()=>window.__fiero.getPartBounds('hl-left-lens'));expect(high.max[1]-low.max[1]).toBeGreaterThan(.15);
 await scope('headlight-relays');await reset();await capture('headlight-relays');expect((await page.evaluate(()=>window.__fiero.getPartBounds('hl-isolation-relay'))).max[0]).toBeLessThan(0);
 await page.getByRole('button',{name:'Back to vehicle',exact:false}).click();await expect(page.locator('canvas')).toHaveAttribute('data-selected','headlights');await reset();const raised=await page.evaluate(()=>window.__fiero.getPartBounds('headlights'));expect(raised.max[1]).toBeLessThan(.89);expect(raised.max[1]-closed.max[1]).toBeGreaterThan(.12);await capture('headlights-vehicle-raised');
 await page.getByRole('button',{name:'Configure',exact:true}).click();await page.getByRole('button',{name:'White paint',exact:true}).click();await page.locator('[data-config="headlights"]').uncheck();await page.getByRole('button',{name:'Exterior',exact:true}).click();await capture('headlights-vehicle-white-closed');
 await page.setViewportSize({width:390,height:700});await page.getByRole('button',{name:'Open assemblies',exact:true}).click();await page.getByRole('searchbox').fill('Output-gear cushion');await page.locator('.part-button[data-part="hl-right-bumper-4"]').click();await expect(page.locator('canvas')).toHaveAttribute('data-assembly','headlight-right-motor');await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();await capture('headlight-mobile-cushion');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.locator('[data-tab="uat"]').click();await page.getByRole('button',{name:'Remaining model & manual work',exact:true}).click();await page.locator('[data-work-assembly="headlight-system"]').click();await expect(page.locator('#modal')).not.toBeVisible();await expect(page.locator('canvas')).toHaveAttribute('data-assembly','headlight-system');expect(errors).toEqual([]);expect(images).toEqual([]);
});
