import {test,expect} from '@playwright/test';
import {detailMembers,detailAvailable} from '../src/inspection-catalog.js';
test('heater and C60 previews share native cores and show distinct controls, motors and refrigeration parts',async({page})=>{
 test.setTimeout(840000);page.setDefaultTimeout(45000);const errors=[],images=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.resourceType()==='image')images.push(r.url());});
 await page.goto('/');await page.waitForFunction(()=>window.__fiero&&document.querySelector('canvas').dataset.ready==='true',null,{timeout:180000});await expect(page.locator('#loading')).toHaveCount(0);
 const capture=async name=>{await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot({path:`artifacts/${name}.png`});console.log('Captured '+name);};
 const scope=async id=>{await page.locator(`#systems [data-assembly="${id}"]`).click();await expect(page.locator('canvas')).toHaveAttribute('data-assembly',id);};const reset=()=>page.getByRole('button',{name:'Reset view',exact:true}).click();
 const members=async(id,airConditioning)=>expect((await page.evaluate(()=>window.__fiero.getVisibleParts())).sort()).toEqual(detailMembers(id).filter(p=>detailAvailable(p,{airConditioning})).map(p=>p.id).sort());
 await capture('vehicle-after-hvac');await page.locator('#systems [data-system="cooling"]').click();await page.locator('.part-button[data-part="hvac-module"]').click();await page.getByRole('button',{name:'Explode this assembly',exact:true}).click();await reset();await members('hvac-system',false);await expect(page.locator('#systems [data-assembly="hvac-evaporator"]')).toHaveCount(0);await capture('hvac-c41-assembled');
 await scope('hvac-module');await reset();await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('hvac-c41-module-exploded');await page.locator('.part-button[data-part="hv-core"]').click();await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();await expect(page.locator('#inspector-content')).toContainText('3052181');await expect(page.locator('#inspector-content a').first()).toHaveAttribute('href',/#page=254$/);
 await scope('hvac-blower');await reset();await capture('hvac-blower-assembled');await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('hvac-blower-exploded');await page.locator('.part-button[data-part="hv-wheel"]').click();await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();await capture('hvac-blower-wheel');
 await scope('hvac-ducts');await reset();await capture('hvac-ducts');await scope('hvac-controls');await reset();await capture('hvac-c41-controls');expect((await page.evaluate(()=>window.__fiero.getPartBounds('hv-fan-knob'))).max[0]).toBeLessThan(0);await members('hvac-controls',false);
 await page.getByRole('button',{name:'Configure',exact:true}).click();await page.locator('#config-airConditioning').check();await page.locator('[data-tab="component"]').click();await members('hvac-controls',true);await expect(page.locator('.part-button[data-part="hv-mode-slider"]')).toHaveCount(0);await expect(page.locator('.part-button[data-part="hv-mode-buttons"]')).toHaveCount(1);await capture('hvac-c60-controls');
 await scope('hvac-system');await reset();await members('hvac-system',true);await capture('hvac-c60-assembled');await scope('hvac-module');await reset();await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('hvac-c60-module-exploded');
 await scope('hvac-evaporator');await reset();await capture('hvac-evaporator-assembled');await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('hvac-evaporator-exploded');await page.locator('.part-button[data-part="hv-orifice"]').click();await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();await capture('hvac-orifice-tube');
 // Disabling C60 while inside its exclusive scope must recover to a useful
 // heater view and clear the now-hidden selection, not leave an empty canvas.
 await page.getByRole('button',{name:'Configure',exact:true}).click();await page.locator('#config-airConditioning').uncheck();await page.locator('[data-tab="component"]').click();await expect(page.locator('canvas')).toHaveAttribute('data-assembly','hvac-system');await expect(page.locator('canvas')).toHaveAttribute('data-selected','');await members('hvac-system',false);await expect(page.locator('#stage-title')).toHaveText('Heating & ventilation');await capture('hvac-auto-scope-recovery');const camera=await page.evaluate(()=>window.__fiero.getCamera());expect(Math.hypot(...camera.position.map((n,i)=>n-camera.target[i]))).toBeGreaterThan(1);await reset();
 await scope('cooling-system');await scope('cool-heater');await reset();await capture('hvac-shared-coolant-core');await page.getByRole('button',{name:'Back to vehicle',exact:false}).click();await expect(page.locator('canvas')).toHaveAttribute('data-selected','hvac-module');await reset();await page.getByRole('button',{name:'Configure',exact:true}).click();await page.locator('#config-airConditioning').check();await page.getByRole('button',{name:'Cabin',exact:true}).click();await capture('hvac-cabin-controls-visible');const cabinParts=await page.evaluate(()=>window.__fiero.getVisibleParts());for(const id of ['hvac-controls','hvac-ducts','door-trim-left','door-trim-right'])expect(cabinParts).toContain(id);
 await page.setViewportSize({width:390,height:700});await page.getByRole('button',{name:'Open assemblies',exact:true}).click();await page.getByRole('searchbox').fill('centrifugal blower');await page.locator('.part-button[data-part="hv-wheel"]').click();await expect(page.locator('canvas')).toHaveAttribute('data-assembly','hvac-blower');await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();await capture('hvac-mobile');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);expect(images).toEqual([]);
});
