import {test,expect} from '@playwright/test';
import {engineMembers} from '../src/engine-catalog.js';

test('global ICM search opens the nested distributor, separates parts and restores the vehicle',async({page})=>{
 test.setTimeout(300000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.waitForFunction(()=>window.__fiero);
 await page.locator('#explode').fill('20');
 await page.getByRole('searchbox').fill('ICM');
 await expect(page.locator('.part-button[data-part="eng-icm"]')).toContainText('Engine / Distributor & ICM');
 await page.locator('.part-button[data-part="eng-icm"]').click();
 await expect(page.locator('canvas')).toHaveAttribute('data-assembly','distributor-detail');
 await expect(page.locator('.component-heading')).toContainText('Ignition control module');
 await expect(page.locator('.part-button')).toHaveCount(engineMembers('distributor-detail').length);
 await expect(page.locator('#inspector-content')).toContainText('1103633');
 await expect(page.locator('#inspector-content a[target="_blank"]')).toHaveAttribute('href',/page=65/);
 await page.getByRole('button',{name:'Reset view',exact:true}).click();
 const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
 await settle();
 const ids=['eng-cap','eng-rotor','eng-icm','eng-pickup-coil','eng-distributor'];
 const before=await page.evaluate(ids=>Object.fromEntries(ids.map(id=>[id,window.__fiero.getPartBounds(id)])),ids);
 await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await settle();
 const after=await page.evaluate(ids=>Object.fromEntries(ids.map(id=>[id,window.__fiero.getPartBounds(id)])),ids);
 expect(after['eng-cap'].min[1]-before['eng-cap'].min[1]).toBeCloseTo(.33,3);
 expect(after['eng-rotor'].min[1]-before['eng-rotor'].min[1]).toBeCloseTo(.225,3);
 expect(after['eng-icm'].min[0]-before['eng-icm'].min[0]).toBeCloseTo(-.13,3);
 expect(after['eng-pickup-coil'].min[0]-before['eng-pickup-coil'].min[0]).toBeCloseTo(.12,3);
 expect(after['eng-distributor']).toEqual(before['eng-distributor']);
 await page.locator('.part-button[data-part="eng-icm"]').click();await page.getByRole('button',{name:'Isolate',exact:true}).click();
 expect(await page.evaluate(()=>window.__fiero.getVisibleParts())).toEqual(['eng-icm']);
 await page.locator('#systems [data-assembly="ignition"]').click();
 expect((await page.evaluate(()=>window.__fiero.getVisibleParts())).sort()).toEqual(engineMembers('ignition').map(p=>p.id).sort());
 await page.locator('#systems [data-assembly="coil-detail"]').click();
 await expect(page.locator('.part-button[data-part="eng-coil-primary-harness"]')).toBeVisible();
 await expect(page.locator('.part-button[data-part="eng-coil-lead"]')).toHaveCount(0);
 await page.locator('#systems [data-assembly="plug-wires"]').click();
 await expect(page.locator('.part-button[data-part="eng-coil-lead"]')).toHaveCount(1);
 await expect(page.locator('.part-button[data-part^="eng-wire-"]')).toHaveCount(7);
 await page.locator('.part-button[data-part="eng-spark-rear-1"]').click();
 await expect(page.locator('.part-service-reference')).toContainText('1.1 mm (0.045 in.)');
 await expect(page.locator('.part-service-reference')).toContainText('15 N·m (11 lb-ft)');
 await expect(page.locator('.part-service-reference')).toContainText('R42CTS');
 await expect(page.locator('.part-service-reference a').first()).toHaveAttribute('href',/page=31/);
 await page.getByRole('button',{name:'Back to vehicle',exact:false}).click();
 expect(await page.evaluate(()=>window.__fiero.getState().assembly)).toBeNull();
 await expect(page.getByRole('searchbox')).toHaveValue('ICM');await expect(page.locator('#explode')).toHaveValue('20');
 await page.getByRole('searchbox').fill('pickup coil');await expect(page.locator('.part-button[data-part="eng-pickup-coil"]')).toBeVisible();
 expect(errors).toEqual([]);
});

test('electrical catalogue exposes ignition assemblies and mobile tune-up navigation',async({page})=>{
 test.setTimeout(240000);await page.setViewportSize({width:390,height:844});
 await page.goto('/');await page.waitForFunction(()=>window.__fiero);
 await page.getByRole('button',{name:'Open assemblies',exact:true}).click();
 await page.locator('#systems [data-system="electrical"]').click();
 await page.locator('.part-button[data-part="distributor"]').click();
 await page.getByRole('button',{name:'Explode this assembly',exact:true}).click();
 await expect(page.locator('canvas')).toHaveAttribute('data-assembly','distributor-detail');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Open assemblies',exact:true}).click();
 await page.getByRole('searchbox').fill('ICM');
 await expect(page.locator('.part-button[data-part="eng-icm"]')).toBeInViewport();
 await page.locator('.part-button[data-part="eng-icm"]').click();
 await expect(page.locator('.sidebar')).not.toHaveClass(/mobile-open/);
 await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();
 await page.screenshot({path:'artifacts/ignition-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Back to vehicle',exact:false}).click();
 await expect(page.locator('canvas')).toHaveAttribute('data-selected','distributor');
});
