import {waitForViewer,evaluateViewer} from './viewer-ready.js';
import {test,expect} from '@playwright/test';
import {detailMembers,detailAvailable} from '../src/inspection-catalog.js';
import {defaultConfiguration} from '../src/configuration.js';
test('Interior I1 is shared by the manual, explodes seats and trim, and links existing instrument components',async({page})=>{
 test.setTimeout(720000);page.setDefaultTimeout(60000);page.setDefaultNavigationTimeout(240000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.waitForFunction(()=>window.__fiero&&document.querySelector('canvas').dataset.ready==='true',null,{timeout:240000});
 await expect(page.locator('.build-badge')).toContainText('INTERIOR I1');
 const capture=async name=>{await waitForViewer(page);await page.locator('#viewport').screenshot({path:`artifacts/interior-i1-manual-${name}.png`});};
 await page.getByRole('button',{name:'Configure',exact:true}).click();await page.getByRole('button',{name:'Cabin',exact:true}).click();await page.locator('[data-tab="component"]').click();await capture('cabin');
 await page.locator('#systems [data-system="interior"]').click();await page.locator('.part-button[data-part="seats"]').click();await page.getByRole('button',{name:'Explode this assembly',exact:true}).click();
 await waitForViewer(page);await expect(page.locator('canvas')).toHaveAttribute('data-assembly','interior-system');
 const scope=async id=>{await page.locator(`#systems [data-assembly="${id}"]`).click();await waitForViewer(page);await expect(page.locator('canvas')).toHaveAttribute('data-assembly',id);await page.getByRole('button',{name:'Reset view',exact:true}).click();};
 await scope('interior-seat-left');expect((await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).sort()).toEqual(detailMembers('interior-seat-left').filter(p=>detailAvailable(p,defaultConfiguration)).map(p=>p.id).sort());await capture('seat');
 await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await capture('seat-exploded');
 await page.locator('.part-button[data-part="in-seat-left-floor-nut-0"]').click();await page.getByRole('button',{name:'Isolate',exact:true}).click();expect(await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).toEqual(['in-seat-left-floor-nut-0']);await expect(page.locator('#inspector-content')).toContainText('front inner');
 await scope('interior-door-left');expect(await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).toContain('in-door-left-crank');
 await page.getByRole('button',{name:'Configure',exact:true}).click();await page.locator('#config-powerWindows').check();await page.locator('[data-tab="component"]').click();expect(await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).not.toContain('in-door-left-crank');await capture('door');
 await scope('interior-console');for(const id of ['in-radio-face','in-shared-center-outlet','in-shared-heater'])expect(await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).toContain(id);await capture('console');
 await scope('interior-dashboard');await page.locator('.part-button[data-part="in-shared-cluster"]').click();await page.getByRole('button',{name:'Open detailed assembly',exact:true}).click();await waitForViewer(page);await expect(page.locator('canvas')).toHaveAttribute('data-assembly','wiring-cluster');expect((await evaluateViewer(page,()=>window.__fiero.getVisibleParts())).length).toBeGreaterThan(40);
 await page.getByRole('button',{name:'Back to vehicle',exact:false}).click();await page.getByRole('button',{name:'Reset view',exact:true}).click();
 await page.setViewportSize({width:390,height:760});await page.getByRole('button',{name:'Open assemblies',exact:true}).click();await page.getByRole('searchbox').fill('Passenger Cushion steel pan');await page.locator('.part-button[data-part="in-seat-right-pan"]').click();await waitForViewer(page);await expect(page.locator('canvas')).toHaveAttribute('data-assembly','interior-seat-right');await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();await capture('mobile-pan');
 expect(await evaluateViewer(page,()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
