import {test,expect} from '@playwright/test';
import {engineMembers} from '../src/engine-catalog.js';

test('oil pump construction opens, explodes, isolates and returns on desktop and mobile',async({page})=>{
 test.setTimeout(420000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.waitForFunction(()=>window.__fiero);
 const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
 const capture=async name=>{await settle();await page.screenshot({path:`artifacts/oil-pump-${name}.png`});};
 await page.locator('#systems [data-system="engine"]').click();
 await page.locator('.part-button[data-part="oil-pan"]').click();
 await page.getByRole('button',{name:'Explore engine components',exact:true}).click();
 await page.locator('#systems [data-assembly="lubrication"]').click();
 await page.locator('#systems [data-assembly="oil-pump-detail"]').click();
 await expect(page.locator('.part-button')).toHaveCount(12);
 expect((await page.evaluate(()=>window.__fiero.getVisibleParts())).sort()).toEqual(engineMembers('oil-pump-detail').map(p=>p.id).sort());
 await page.getByRole('button',{name:'Reset view',exact:true}).click();await capture('assembled');
 const before=await page.evaluate(()=>Object.fromEntries(['eng-oil-pump','eng-oil-pump-cover','eng-oil-pump-drive-gear','eng-pickup-screen'].map(id=>[id,window.__fiero.getPartBounds(id)])));
 await page.getByRole('button',{name:'Explode assembly',exact:true}).click();await settle();
 const after=await page.evaluate(()=>Object.fromEntries(['eng-oil-pump','eng-oil-pump-cover','eng-oil-pump-drive-gear','eng-pickup-screen'].map(id=>[id,window.__fiero.getPartBounds(id)])));
 expect(after['eng-oil-pump']).toEqual(before['eng-oil-pump']);
 expect(after['eng-oil-pump-cover'].min[1]-before['eng-oil-pump-cover'].min[1]).toBeCloseTo(-.20,3);
 expect(after['eng-oil-pump-drive-gear'].min[1]-before['eng-oil-pump-drive-gear'].min[1]).toBeCloseTo(-.10,3);
 expect(after['eng-pickup-screen'].min[1]-before['eng-pickup-screen'].min[1]).toBeCloseTo(-.12,3);
 await capture('exploded');
 await page.locator('.part-button[data-part="eng-oil-pump-drive-gear"]').click();
 await expect(page.locator('#inspector-content')).toContainText('not a verified original tooth count');
 await expect(page.locator('#inspector-content')).toContainText('not an overhaul procedure');
 await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();
 expect(await page.evaluate(()=>window.__fiero.getVisibleParts())).toEqual(['eng-oil-pump-drive-gear']);await capture('drive-gear');
 await page.getByRole('button',{name:'Show context',exact:true}).click();
 expect((await page.evaluate(()=>window.__fiero.getVisibleParts())).length).toBe(12);
 await page.getByRole('button',{name:'Back to vehicle',exact:false}).click();
 await expect(page.locator('canvas')).toHaveAttribute('data-selected','oil-pan');
 expect(await page.evaluate(()=>window.__fiero.getState().system)).toBe('engine');
 await page.setViewportSize({width:390,height:600});await page.getByRole('button',{name:'Open assemblies',exact:true}).click();
 await page.getByRole('searchbox').fill('relief piston');await page.locator('.part-button[data-part="eng-oil-pump-relief-piston"]').click();
 await expect(page.locator('canvas')).toHaveAttribute('data-assembly','oil-pump-detail');
 await expect(page.locator('.sidebar')).not.toHaveClass(/mobile-open/);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Focus part',exact:true}).click();
 expect(await page.evaluate(()=>window.__fiero.getVisibleParts())).toEqual(['eng-oil-pump-relief-piston']);await page.locator('canvas').scrollIntoViewIfNeeded();await settle();await page.screenshot({path:'artifacts/oil-pump-mobile-relief.png',fullPage:true});
 expect(errors).toEqual([]);
});
