import {exhaustParts,exhaustSections} from './exhaust-catalog.js';
import {engineParts,engineSections} from './engine-catalog.js';
import {transmissionParts,transmissionSections} from './transmission-catalog.js';
import {coolingParts,coolingSections} from './cooling-catalog.js';
import {brakeParts,brakeSections} from './brake-catalog.js';
import {suspensionParts,suspensionSections} from './suspension-catalog.js';
import {fuelParts,fuelSections} from './fuel-catalog.js';
export const detailFamilies={
 'exhaust-system':{id:'exhaust-system',name:'Exhaust',shortName:'V6 exhaust',system:'fuel',icon:'gear',kicker:'1985 / L44 EXHAUST',coverage:'Manifolds, crossover and shields, spring-loaded downpipe joint, early pellet converter cutaway, transverse muffler, twin tailpipes, clamps, shields and spring hangers. Catalogued 1985–86 assemblies are distinguished from later applications. Local bends, exact profiles, clearances, pellet count and muffler internals remain unverified. Welded-part separation illustrates construction, not a removal procedure.'},
 'fuel-system':{id:'fuel-system',name:'Fuel',shortName:'V6 fuel supply',system:'fuel',icon:'gear',kicker:'1985 / L44 FUEL SUPPLY',coverage:'Early tank shells, straps, pump/sender, driver-side filler, filter, distinct feed/return routes, vapor canister and pump relay. Welded shell separation is an illustrative cutaway. Detailed dimensions, factory routing, pump internals and sender calibration remain unverified; the typical 1986 pump drawing is adjacent-year evidence.'},
 'suspension-system':{id:'suspension-system',name:'Suspension',shortName:'Suspension / steering',system:'suspension',icon:'gear',kicker:'1985 / WS6 ARCHITECTURE',coverage:'Separate front shocks and coils, formed control arms, ball joints, bushings, rear strut stacks and toe links, early cradle, 23 mm front stabilizer, manual steering rack and passenger-side damper. Spring rates/codes, tooth counts, local pivot coordinates and exact stamped/cast profiles remain unverified. Hubs and knuckles can be inspected in the Brakes explorer.'},
 engine:{id:'engine',name:'Engine',shortName:'2.8L V6',system:'engine',icon:'engine',kicker:'L44 / 2.8L V6',coverage:'Engine internals, ignition and service hardware. Measured castings, complete passages, routing and some accessory internals remain incomplete.'},
 transmission:{id:'transmission',name:'Transmission',shortName:'Four-speed',system:'drivetrain',icon:'gear',kicker:'FOUR-SPEED / 76 MM',coverage:'Case, gear trains, reverse idler, synchronizers, bearings, differential, selector and clutch. Gear profiles and casting dimensions are reconstructed. Detailed hydraulics, CV joints and mounting hardware remain incomplete.'},
 'cooling-system':{id:'cooling-system',name:'Cooling',shortName:'Coolant circuit',system:'cooling',icon:'water',kicker:'L44 / COOLANT CIRCUIT',coverage:'Radiator, fan, asymmetric inlet and return pipes, recovery bottle and heater circuit preview. Hose bends, fan variant, clearances and local dimensions need further verification. Thermostat and water pump can be opened through the engine service views.'},
 'braking-system':{id:'braking-system',name:'Brakes',shortName:'1985 brakes',system:'brakes',icon:'disc',kicker:'1985 / FOUR-WHEEL DISC',coverage:'Four separate corners, front integral rotor/hubs, rear hub units, calipers and parking actuators, composite master, tandem booster, lines and cables. Nominal rotor dimensions follow the 1985 DIY manual. Casting profiles, detailed fits, hose clearances, rear piston clutch internals and valve calibration remain unverified.'},
};
export const detailParts=[...exhaustParts.map(p=>({...p,family:'exhaust-system'})),...fuelParts.map(p=>({...p,family:'fuel-system'})),...suspensionParts.map(p=>({...p,family:'suspension-system'})),...engineParts.map(p=>({...p,family:'engine'})),...transmissionParts.map(p=>({...p,family:'transmission'})),...coolingParts.map(p=>({...p,family:'cooling-system'})),...brakeParts.map(p=>({...p,family:'braking-system'}))];
export const detailSections=[...exhaustSections.map(s=>({...s,family:'exhaust-system'})),...fuelSections.map(s=>({...s,family:'fuel-system'})),...suspensionSections.map(s=>({...s,family:'suspension-system'})),...engineSections.map(s=>({...s,family:'engine',parent:s.id==='engine'?undefined:s.parent||'engine'})),...transmissionSections.map(s=>({...s,family:'transmission'})),...coolingSections.map(s=>({...s,family:'cooling-system'})),...brakeSections.map(s=>({...s,family:'braking-system'}))];
export const detailPartById=new Map(detailParts.map(p=>[p.id,p]));
export const detailSectionById=new Map(detailSections.map(s=>[s.id,s]));
export const familyFor=section=>detailFamilies[detailSectionById.get(section)?.family||'engine'];
export function inDetailSection(part,section){if(!part)return false;let id=part.section;while(id){if(id===section)return true;id=detailSectionById.get(id)?.parent;}return false;}
export const detailMembers=section=>detailParts.filter(p=>inDetailSection(p,section));
