export const vehicle = { year: 1985, make: 'Pontiac', model: 'Fiero SE 2M6', vin: '1G2PF3796FP217611', engine: 'L44 · 2.8L V6', transmission: '4-speed manual', suspension: 'WS6', originality: 'Original equipment — owner reported' };
export const sources = [
  {id:'ignition-catalog',title:'GM L44 distributor · K-13 / GM02-056',url:'https://fieroinfo.com/manuals/84-88_Fiero_Parts_%26_Illustrations_CD.pdf#page=65',note:'Factory V6 distributor drawing and 17 numbered callouts inspected. Establishes cap, rotor, shaft, pickup, pole piece, ICM, shield, seal, gear, washers and pins. Lists two 1985 distributor applications; the installed variant cannot be determined from VIN alone.'},
  {id:'separate-coil',title:'1986 Pontiac factory manual · separate-coil HEI/EST',url:'https://fieroinfo.com/manuals/1986_Fiero_Service_Manual.pdf#page=395',note:'Printed 6D-24, figure 27A inspected for external coil and module connector forms; 6D-40 / 41 inspected for L44 wiring locations. Supporting geometry reference from an adjacent model year, not proof of exact 1985 part interchange or service specifications.'},
  { id:'parts22p',title:'GM Pontiac 22P · parts & illustrations',url:'https://fieroinfo.com/manuals/84-88_Fiero_Parts_%26_Illustrations_P22.pdf',note:'Factory parts catalog, November 1990 edition, covering 1984–88. Inspected H-19 through H-23 for the L44 engine, K-17 / K-18 for front lamps; G-13 / G-19 for SE fascias; H-7 for the carrier and G-10 for the pedestal wing. Catalog numbers are dated references; most parts and interchangeability have not yet been imported or verified.' },
  { id:'6e3',title:'1985 factory service section 6E3 · L44',url:'https://fieroinfo.com/manuals/1985_Fiero_6E3_Emissions_and_Drivability.pdf',note:'Pontiac Service Department publication for 1985, 2.8L L44, VIN engine code 9. Inspected EST figure 38 (6E3-90 / 91), MAP figure 9, throttle figure 25, cold-start figure 30, rail connection figures 31–33 and EGR figure 42. This is an engine-control section, not the complete chassis / body service manual; diagnostic procedures are not yet implemented.' },
  { id:'diy',title:'Pontiac 1985 Do-It-Yourself manual',url:'https://fieroinfo.com/manuals/1985_Fiero_Do_It_Yourself.pdf',note:'Factory publication inspected directly. Printed 1-4 to 1-6: structure and panels; 2-4: front compartment; 2-14: clutch hydraulics; 2-16: V6 air cleaner; 2-28 / 2-29: headlamps; 3-2 and 3-3: dimensions and wheels. Surface contours and hidden mechanisms are reconstructed, not factory CAD.' },
  { id:'lighting',title:'Poly Haven · Studio Small 09',url:'https://polyhaven.com/a/studio_small_09',note:'Free CC0 HDR environment used for studio reflections and lighting. Stored locally. It is not a photograph of the car or a substitute for vehicle geometry.' },
  { id: 'vin', title: 'NHTSA VIN decode', url: 'https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValues/1G2PF3796FP217611?format=json&modelyear=1985', note: 'Confirms model year, SE trim, 2.8L V6, assembly plant and valid VIN check digit. Does not identify the transmission or full option list.' },
  { id: 'brochure', title: '1985 Pontiac Fiero factory brochure', url: 'https://xr793.com/wp-content/uploads/2018/10/1985-Pontiac-Fiero-Cdn.pdf', note: 'Canadian-market brochure. Reference for the L44 V6 / four-speed combination and availability of the Special Performance Package. Not a repair-procedure source.' },
  { id: 'manual', title: 'Factory service manual · S-8510P', url: 'https://www.detroitironis.com/1985-pontiac-fiero-service-manual-print.html', note: 'Reference acquisition link only. Full factory procedures, torque specifications and page references have not yet been imported or verified.' },
  { id: 'owner', title: 'Owner-provided vehicle information', note: 'Original manual-transmission SE, VIN and WS6 supplied by the owner. Factory-new appearance requested. Configurator choices are previews: paint, interior and other options cannot be inferred from this VIN.' }
];
export const systems = [
  { id: 'all', name: 'Whole vehicle', icon: 'car', subtitle: 'All assemblies', color: '#ca4e38' },
  { id: 'body', name: 'Body & chassis', icon: 'layers', subtitle: 'Panels, structure & glass', color: '#ce5140' },
  { id: 'engine', name: 'Engine & intake', icon: 'engine', subtitle: 'L44 · 2.8L V6', color: '#d9a760' },
  { id: 'drivetrain', name: 'Transmission & clutch', icon: 'gear', subtitle: '4-speed manual', color: '#889bb8' },
  { id: 'suspension', name: 'Suspension & steering', icon: 'spring', subtitle: 'WS6 package', color: '#79b8ae' },
  { id: 'brakes', name: 'Brakes & wheels', icon: 'disc', subtitle: 'Four-wheel disc layout', color: '#b89dcd' },
  { id: 'cooling', name: 'Cooling system', icon: 'water', subtitle: 'Front-to-rear circuit', color: '#64b8d2' },
  { id: 'fuel', name: 'Fuel & exhaust', icon: 'flow', subtitle: 'Tank, delivery & exhaust', color: '#bf946f' },
  { id: 'electrical', name: 'Electrical', icon: 'bolt', subtitle: 'Power & ignition', color: '#d4bb62' },
  { id: 'interior', name: 'Interior & controls', icon: 'seat', subtitle: 'Cockpit & controls', color: '#aaa79a' }
];
const p = (id, system, name, description, location, extra = {}) => ({ id, system, name, description, location, geometry: 'Illustrative', verification: 'Factory verification pending', ...extra });
export const parts = [
 p('spaceframe','body','Space frame','Welded steel structure reconstructed from factory DIY 1-4 / 1-5: formed rails, open door apertures, floor pans, tunnel, wheelhouses and bulkheads. Local dimensions, welds and mounting coordinates are approximate; this is not a body-alignment model.','Full vehicle'),
 p('hood','body','Front hood','Opening panel above the front storage and cooling-system area.','Front compartment'),
 p('nose','body','Front fascia','Rounded 1985 SE bumper-pad nose with a sloping upper surface, wrapped moldings, inset park lamps and a rolled-under lower edge. Reconstructed from GM 22P G-13 and the period brochure; local contours are not measured.','Front'),
 p('rear-fascia','body','Rear fascia','Rounded SE rear fascia with paired lower bumper pads and a central plate recess, following GM 22P G-19. The raked lamp panel blends into the rear deck edge; local contours remain reconstructed.','Rear'),
 p('fender-left','body','Left front fender','Left front wheel-opening body panel.','Front left'),
 p('fender-right','body','Right front fender','Right front wheel-opening body panel.','Front right'),
 p('quarter-left','body','Left rear quarter','Rear side body panel around the engine compartment.','Rear left'),
 p('quarter-right','body','Right rear quarter','Rear side body panel around the engine compartment.','Rear right'),
 p('door-left','body','Left door','Driver-side door assembly. Internal hardware is not yet modeled.','Left side'),
 p('door-right','body','Right door','Passenger-side door assembly. Internal hardware is not yet modeled.','Right side'),
 p('roof','body','Front roof & A-pillars','Formed front roof skin and A-pillars with solid and removable-glass previews. The rear roof clip and sail windows are separate selectable assemblies. Original roof equipment remains unconfirmed.','Cabin'),
 p('rear-clip','body','Rear roof clip & C-pillars','Extended rear roof header, broad painted C-pillars and curved inner buttresses surrounding the recessed backlight. Reconstructed from GM 22P H-8 and supplied reference images; local contours are not measured.','Behind cabin'),
 p('sail-left','body','Left sail window & frame','Small, framed opaque notchback quarter-window applique ahead of the painted C-pillar. It is separate from the door glass and rear window; reconstructed from the supplied close-up and GM 22P H-8.','Left rear roof'),
 p('sail-right','body','Right sail window & frame','Small, framed opaque notchback quarter-window applique ahead of the painted C-pillar. Mounting details remain illustrative.','Right rear roof'),
 p('rear-window','body','Rear window / backlight','Recessed rear glass beneath the extended roof header, with rounded corners and an optional defroster preview. The reconstructed outline is not a replacement-glass template.','Rear of cabin'),
 p('deck-vent-left','body','Left engine-deck vent grille','Removable louvred grille alongside the raised center of the rear decklid. Separate selectable geometry follows the 1985 panel layout.','Left engine deck'),
 p('deck-vent-right','body','Right engine-deck vent grille','Removable louvred grille alongside the raised center of the rear decklid. Separate selectable geometry follows the 1985 panel layout.','Right engine deck'),
 p('glass','body','Cabin glazing','Windshield and door glass. The recessed rear window is selectable separately.','Cabin'),
 p('decklid','body','Rear decklid','Shaped rear decklid with a raised forward center and a wider rear trunk section. The removable vent grilles beside it are separate assemblies. Options include the V56 carrier with integral spoiler (GM 22P H-7) and a curved pedestal-wing preview (G-10); neither establishes this car’s original option selection.','Rear compartment'),
 p('engine-block','engine','V6 cylinder block','Illustrative transverse V6 engine assembly. Internal dimensions and castings are not engineering geometry.','Behind cabin'),
 p('heads','engine','Cylinder heads & valve covers','Two cylinder banks represented with removable covers for assembly exploration.','Engine bay'),
 p('intake','engine','Upper intake plenum','Upper intake assembly feeding the V6. The GM catalog distinguishes the 1985–86 plenum from the 1987–88 part; the reconstructed casting is not measured geometry.','Top of engine',{catalog:{number:'10033120',applies:'1985–86 L44 upper plenum',reference:'GM 22P · H-23, item 6 · November 1990',url:'https://fieroinfo.com/manuals/84-88_Fiero_Parts_%26_Illustrations_P22.pdf#page=18'}}),
 p('air-cleaner','engine','Air cleaner housing','Intake air-filter housing. Explore the cover, filter element and housing in the guided tour.','Left side of engine bay'),
 p('air-filter','engine','Air filter element','Illustrative filter element inside the air-cleaner housing. Replacement specification is pending.','Inside air cleaner'),
 p('air-lid','engine','Air cleaner cover','Removable air-cleaner cover shown separately for the assembly demonstration.','Top of air cleaner'),
 p('intake-duct','engine','Intake duct','Schematic connection between the air cleaner and intake.','Engine bay'),
 p('engine-controls','engine','Engine sensors, valves & lines','Selectable TPS, IAC, MAP sensor, PCV, EGR, cold-start injector, fuel tubes and vacuum hoses. Open the assembly for individual components and factory references. Routing and local dimensions remain reconstructed.','Top and sides of engine',{assembly:'engine-controls'}),
 p('oil-pan','engine','Engine oil pan','Lower engine oil reservoir. Capacity, oil grade and fastener torques are not yet verified.','Under engine'),
 p('gearbox','drivetrain','Four-speed transaxle','Reconstructed manual transmission and final-drive housing on the driver side of the transverse V6. Exact castings and internal gears remain unverified.','Driver side of engine bay'),
 p('clutch','drivetrain','Clutch & flywheel','Illustrative clutch location between the engine and transaxle.','Engine / transaxle interface'),
 p('axles','drivetrain','Rear drive axles','Schematic half-shafts connecting the transaxle to the driven rear wheels.','Rear axle line'),
 p('shift-linkage','drivetrain','Shift cable route','Conceptual route from the gear lever to the transaxle. Actual routing and attachments need verification.','Centre tunnel to transaxle'),
 p('clutch-hydraulics','drivetrain','Clutch master cylinder & hydraulics','Factory DIY 2-4 and 2-14 identify the clutch-fluid reservoir beside the brake booster on the driver side. The line and slave-cylinder route is illustrative.','Front driver side to transaxle'),
 p('cradle','suspension','Rear engine cradle','Schematic rear support structure for the powertrain and rear suspension.','Under engine bay'),
 p('front-arms','suspension','Front control arms','Illustrative front suspension arms. Pivot coordinates are approximate.','Front suspension'),
 p('rear-arms','suspension','Rear control arms','Illustrative links between the rear cradle and wheel carriers.','Rear suspension'),
 p('front-springs','suspension','Front springs & dampers','WS6 configuration selected. Exact spring codes, rates and damper specifications remain unverified.','Front suspension'),
 p('rear-struts','suspension','Rear struts & springs','Illustrative rear strut assemblies. WS6-specific parts require the factory parts references.','Rear suspension'),
 p('steering-rack','suspension','Steering rack & tie rods','Schematic rack-and-pinion steering assembly. Ratio is not yet verified.','Front axle area'),
 p('stabilizer','suspension','Front stabilizer bar','Illustrative front anti-roll bar. Diameter and bushings are pending verification.','Front suspension'),
 p('wheels','brakes','Wheels & tires','Reconstructed 14-inch Hi-Tech-style alloys with P215/60R14 tire envelopes from the WS6 brochure. Wheel contours are approximate; tire pressures and specific wheel part numbers remain unverified.','Four corners'),
 p('spare-wheel','brakes','Compact spare & jack','Front-compartment spare and jack placement follows the factory DIY 2-4 illustration. Tire size, pressure and retaining hardware are not verified.','Front compartment'),
 p('front-rotors','brakes','Front brake rotors','Front disc-brake assemblies. Thickness limits and service specifications await verification.','Front hubs'),
 p('rear-rotors','brakes','Rear brake rotors','Rear disc-brake assemblies. Parking-brake mechanism is not yet modeled.','Rear hubs'),
 p('calipers','brakes','Brake calipers','Illustrative caliper locations at each wheel.','Four corners'),
 p('master-cylinder','brakes','Brake master cylinder & booster','Illustrative hydraulic master-cylinder and booster assembly.','Front compartment'),
 p('radiator','cooling','Radiator & fan','Front-mounted heat exchanger and schematic fan.','Front compartment'),
 p('coolant-pipes','cooling','Underbody coolant pipes','Schematic long coolant paths between the front radiator and rear engine.','Both sides of underbody'),
 p('thermostat','cooling','Thermostat housing','Illustrative engine-side coolant housing.','Engine bay'),
 p('coolant-reservoir','cooling','Coolant recovery reservoir','Front-compartment recovery tank shown in factory DIY 2-4. Shape, capacity, level markings and hose routing are reconstructed.','Front passenger side'),
 p('fuel-tank','fuel','Fuel tank','Schematic tank occupying the central underbody area.','Centre tunnel'),
 p('fuel-lines','fuel','Fuel supply route','Conceptual route only; fittings and actual line paths require verification.','Tank to engine'),
 p('exhaust','fuel','Exhaust system','Simplified exhaust path and rear muffler. Catalyst, heat shields and detailed manifold routing are not yet modeled.','Engine bay / rear underbody'),
 p('battery','electrical','Battery','Illustrative battery and terminals. Original mounting details require verification.','Engine bay'),
 p('distributor','electrical','Distributor & ignition control module','L44 distributor with cap, rotor, ICM, pickup coil, magnetic pole pieces, shaft, drive gear and retaining hardware. Open the assembly to inspect each modeled component.','Driver side of engine',{assembly:'distributor-detail'}),
 p('ignition-coil','electrical','Ignition coil, harnesses & tach filter','Single external coil with bracket, primary harness, EST connector and tachometer filter. Open the assembly to separate the modeled components.','Beside distributor',{assembly:'coil-detail'}),
 p('ignition-leads','electrical','Spark plugs & ignition leads','Six detailed spark plugs and individual HT leads, plus the coil-to-cap lead and wire separators. Wire routes are reconstructed; position labels are not a firing-order diagram.','Both cylinder banks',{assembly:'plug-wires'}),
 p('alternator','electrical','Alternator','Schematic engine-driven charging component.','Engine accessory area'),
 p('headlights','electrical','Headlamp assemblies','Raised and closed headlamps reconstructed from factory DIY 2-28 / 2-29 and GM 22P K-17 / K-18: hinged covers, rounded bezels, sealed-beam reflectors, glass lenses and first-generation actuator layout. Local dimensions and linkage paths remain approximate.','Front corners'),
 p('taillights','electrical','Rear lamp assemblies','Reconstructed notchback rear lamps: a raked, divided smoked-lens panel with optical grids and inboard reverse sections.','Rear fascia'),
 p('harness','electrical','Main harness route','Conceptual wiring route. This is not a wiring diagram or pinout.','Front, cabin and engine bay'),
 p('washer-reservoir','electrical','Windshield washer reservoir','Front-compartment washer bottle shown in factory DIY 2-4. Bottle, pump and line are a reference reconstruction.','Front driver side'),
 p('seats','interior','Bucket seats','Contoured buckets with integrated headrests and optional speaker-grille geometry, reconstructed from the factory brochure. Original upholstery and trim colour remain unconfirmed.','Cabin'),
 p('dashboard','interior','Dashboard & instruments','Illustrative dashboard, instrument cluster and centre controls.','Cabin'),
 p('steering-wheel','interior','Steering wheel & column','Driver controls connected visually to the steering area.','Driver side'),
 p('shifter','interior','Manual gear lever','Four-speed manual gear-lever representation.','Centre console'),
 p('pedals','interior','Clutch, brake & accelerator','Three-pedal layout for the original manual transmission.','Driver footwell')
];
export const tours = [
 { id:'orientation', title:'Meet the mid-engine layout', subtitle:'5 stops · vehicle orientation', system:'all', steps:[
   { title:'Start with the whole vehicle', text:'Orbit the vehicle to explore the SE proportions. All shapes in this UAT build are illustrative.', system:'all', camera:'home' },
   { title:'Engine behind the cabin', text:'The V6 is represented behind the two-seat cockpit. Select a component to inspect its record.', system:'engine', part:'engine-block', camera:'rear' },
   { title:'Manual transaxle', text:'Explore the transaxle beside the engine, then trace the rear drive axles. Internal gears are not modeled.', system:'drivetrain', part:'gearbox', camera:'rear' },
   { title:'Cooling across the vehicle', text:'Follow the schematic underbody coolant pipes from the engine area to the front radiator. Exact hose routing is pending.', system:'cooling', part:'coolant-pipes', camera:'side' },
   { title:'WS6 suspension', text:'Explore the front springs and rear struts. This car’s WS6 option is owner-confirmed; exact component specifications remain pending.', system:'suspension', part:'rear-struts', camera:'rear' }
 ]},
 { id:'air-cleaner', title:'Air cleaner assembly', subtitle:'5 steps · exploded assembly demo', system:'engine', steps:[
   { title:'Locate the air cleaner', text:'This is an assembly demonstration, not a validated replacement procedure. Tool sizes, fastener details and access prerequisites are not yet documented.', system:'engine', part:'air-cleaner', camera:'rear', explode:0 },
   { title:'Identify the cover', text:'The highlighted cover belongs above the filter element. Its mounting details need comparison with the factory manual.', system:'engine', part:'air-lid', camera:'rear', explode:0 },
   { title:'Separate the cover', text:'The cover moves vertically to expose the relationship between parts. Animation clearance is illustrative.', system:'engine', part:'air-lid', camera:'rear', explode:0.55 },
   { title:'Inspect the filter element', text:'The filter is highlighted between the cover and lower housing. No replacement part number or service interval has been verified.', system:'engine', part:'air-filter', camera:'rear', explode:1 },
   { title:'Return to the assembled view', text:'The model returns to its assembled state. A workshop-ready procedure will also require verified fastening, sealing and final inspection instructions.', system:'engine', part:'air-cleaner', camera:'rear', explode:0 }
 ]},
 { id:'suspension', title:'Explore the WS6 chassis', subtitle:'5 stops · suspension orientation', system:'suspension', steps:[
   { title:'Front control arms', text:'Inspect the schematic control-arm layout. Suspension pivot locations are not measured engineering data.', system:'suspension', part:'front-arms', camera:'front' },
   { title:'Front springs and dampers', text:'The spring and damper assemblies are separated visually from the body. Spring rates and removal procedures are pending factory verification.', system:'suspension', part:'front-springs', camera:'front' },
   { title:'Steering assembly', text:'Select the rack and tie rods to follow their relationship to the front wheels. The steering ratio has not been verified.', system:'suspension', part:'steering-rack', camera:'top' },
   { title:'Rear cradle', text:'The cradle is shown beneath the rear powertrain area. This tour does not authorize or describe cradle removal.', system:'suspension', part:'cradle', camera:'rear' },
   { title:'Rear struts', text:'Inspect the rear springs and struts. Exact WS6 part selection requires the remaining spring codes and factory parts catalog.', system:'suspension', part:'rear-struts', camera:'rear' }
 ]}
];
export const acceptance = [
 'Orbit, zoom and switch between all five camera views.',
 'Select every system and verify the part list updates.',
 'Search for a component and focus it in the 3D viewer.',
 'Select a part directly on the model.',
 'Hide body panels, isolate a part and restore the vehicle.',
 'Move the exploded-view slider and reset the assembly.',
 'Complete each guided tour and navigate backward.',
 'Review specifications and their verification status.',
 'Save a note, reload the page and export UAT feedback.',
 'Use the explorer on a phone or narrow browser window.'
];
