// An audit of known gaps, not a claim to have enumerated the complete BOM.
export const coverageAudit=[
 {system:'Body & chassis',modeled:'Exterior skins, glazing, roof variants, spoiler previews, headlamp mechanisms and space frame.',remaining:'Door internals, locks, hinges, weatherstrip profiles, panel retainers and exact structural stampings.'},
 {system:'Engine & intake',modeled:'Block and rotating parts, individual valve gear with stamped rockers and separate retaining hardware, intake, oil system, dipstick, early oil-pressure sender, timing seals/guide, sensors, fuel tubes, PCV and EGR.',remaining:'Measured castings, all oil/coolant passages, complete gasket and fastener inventory, exhaust shields and accessory internals.'},
 {system:'Ignition & electrical',modeled:'Detailed distributor stack, ICM, pickup, remote coil, plugs, HT leads, primary/EST leads and tach filter; vehicle lamps, battery and alternator.',remaining:'Verified factory lead routes and cylinder mapping, full vehicle loom, ground straps, junctions, switches, relay/fuse internals and exact distributor variant.'},
 {system:'Transmission & clutch',modeled:'Detailed hollow transaxle castings, input/output gear stacks, synchronizers, reverse, bearings, differential, selector, sprung clutch and release gear; separate unequal halfshafts.',remaining:'Measured involute tooth profiles, original tooth counts and casting dimensions, CV internals, detailed hydraulics and complete mounting hardware.'},
 {system:'Suspension & steering',modeled:'216 selections: formed front/rear arms and frames, ball joints, pivot bushings, separate front shocks and coils, rear strut stacks and toe links, 23 mm front stabilizer, manual rack internals and passenger-side steering damper.',remaining:'Measured frame/arm profiles and pivot coordinates, exact WS6 spring codes/rates, original pinion tooth count/ratio, damper internals, steering column joints and verified travel/clearances.'},
 {system:'Brakes & wheels',modeled:'212 brake selections: four separate calipers/pad sets, front integral rotor/hubs and tapered bearings, rear rotors/hub units, parking actuators/cables, composite master, tandem booster, hard lines/hoses and pedal hardware; existing wheel/tire previews and spare.',remaining:'Measured casting contours, rear piston clutch and sealed-hub internals, valve calibration, verified full-travel hose clearance, exact mounting coordinates, tire/wheel surface accuracy and validated repair procedures.'},
 {system:'Cooling & climate',modeled:'Tube-and-fin radiator, tanks, swept fan/shroud/motor, distinct inlet/return pipes and hoses, clamps, recovery tank, heater circuit preview and detailed engine thermostat/pump exteriors.',remaining:'Water-pump and fan-motor internals, verified fan variant, measured hose routing, heater housing/doors, A/C compressor, condenser, accumulator and option-specific plumbing.'},
 {system:'Fuel & exhaust',modeled:'53 fuel selections: early stepped tank/cutaway shells, straps and pads, pump/sender/float/strainer, driver filler and vent, separate feed/return, in-line filter, vapor canister and pump relay; engine rails/injectors and cold-start components. Exhaust remains a preview.',remaining:'Measured tank/pump geometry and capacity, exact fuel/vapor routing, sender calibration, pump/filter/canister internals, detailed catalyst/exhaust and complete mounting hardware.'},
 {system:'Interior & controls',modeled:'Seats, dashboard, instruments, steering wheel, shifter and pedals.',remaining:'Seat frames/tracks, instrument internals, switch mechanisms, belts, trim attachments and optional accessory hardware.'},
];
