import assert from 'node:assert/strict';
import * as T from 'three';
import {writeFile} from 'node:fs/promises';
globalThis.document={createElement:()=>({getContext:()=>({createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)}),putImageData(){},fillRect(){},strokeRect(){},fillText(){}})})};
const {createWiringDetail,wiringDatums}=await import('../src/wiring-detail.js');const {wiringParts,fusePositions}=await import('../src/wiring-catalog.js');const {estCircuits}=await import('../src/ignition-catalog.js');
const model=createWiringDetail();model.root.updateMatrixWorld(true);const bounds=id=>new T.Box3().setFromObject(model.groups.get('wr-'+id));
assert.equal(fusePositions.length,17);assert.deepEqual(fusePositions.map(f=>f.amps),[10,10,20,20,20,5,20,25,10,5,20,30,5,10,30,20,20]);assert.deepEqual(fusePositions.filter(f=>f.breaker).map(f=>f.number),[12,15]);
for(const p of wiringParts){const g=model.groups.get(p.id);assert(g.children.length,p.id+' empty');g.traverse(m=>{if(!m.isMesh)return;assert(m.geometry.attributes.position.array.every(Number.isFinite),p.id);assert.equal(m.userData.partId,p.id);assert(m.matrixWorld.determinant()>0,p.id);});}
const fuseLocalBounds=n=>{const b=new T.Box3(),p=wiringDatums.fuses,k=Math.SQRT1_2;model.groups.get('wr-fuse-'+n).traverse(m=>{if(!m.isMesh)return;const a=m.geometry.attributes.position;for(let i=0;i<a.count;i++){const v=new T.Vector3().fromBufferAttribute(a,i).applyMatrix4(m.matrixWorld);b.expandByPoint(new T.Vector3(-v.x-p[0],(v.y-p[1]+v.z-p[2])*k,(v.z-p[2]-v.y+p[1])*k));}});return b;};
for(const f of fusePositions){assert(bounds('fuse-'+f.number).max.x<0,'fuses must be driver side');for(const other of fusePositions)if(other.number!==f.number)assert(!fuseLocalBounds(f.number).intersectsBox(fuseLocalBounds(other.number)),`fuses ${f.number}/${other.number} overlap`);}
assert(bounds('turn-flasher').max.x<0);assert(bounds('hazard-flasher').min.x>0);assert(bounds('junction-base').min.x>0);assert(Math.abs(bounds('ecm-base').getCenter(new T.Vector3()).x)<.001);
for(const type of ['ab','cd']){const plug=bounds('ecm-plug-'+type),head=bounds('ecm-header-'+type);assert(plug.max.y<head.min.y,'plugs leave lower open edge');assert(Math.abs(plug.getCenter(new T.Vector3()).x-head.getCenter(new T.Vector3()).x)<.001);}
assert.deepEqual(estCircuits.map(c=>[c.cavity,c.module,c.circuit,c.ecm]),[['A','G',453,'B3'],['B','B',424,'D5'],['C','R',430,'B5'],['D','E',423,'B4']]);
const report={date:new Date().toISOString(),status:'passed',parts:wiringParts.length,checks:['17 factory fuse/breaker ratings and distinct positions','nonempty finite geometry and picking identities','driver fuse panel / turn flasher, passenger hazard flasher / junction','ECM lower-edge connector alignment','1985 figure 38 EST circuit mapping'],limits:'Model audit and transcription assertions; not a circuit continuity test or dimensional certification.'};await writeFile('artifacts/wiring-audit.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
