import {readFile,writeFile,mkdir,stat} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {gzipSync} from 'node:zlib';
import {dirname,resolve,relative} from 'node:path';
import {fileURLToPath} from 'node:url';
import {preserveFiles} from './preserve-files.mjs';
import {auditDetailDelivery,sha256} from './detail-delivery-audit.mjs';
import {disposeModel} from '../src/model-resources.js';

const descriptor='src/detail-manifest.js';
const families={'body-system':{module:'src/body-detail.js',builder:'createBodyDetail',asset:'body'},engine:{module:'src/engine-detail.js',builder:'createEngineDetail',asset:'engine'}};
export async function detailInputs(){
 const files=new Set(['package-lock.json','scripts/build-details.mjs','scripts/detail-delivery-audit.mjs']);
 async function visit(file){
  if(files.has(file))return;files.add(file);
  const source=await readFile(file,'utf8');
  for(const match of source.matchAll(/(?:from\s*|import\s*\()\s*['"](\.[^'"]+)['"]/g)){
   const target=relative(process.cwd(),resolve(dirname(file),match[1]));
   if(!target.startsWith('src/'))throw Error('Unexpected generated-model dependency: '+target);
   await visit(target);
  }
 }
 for(const file of [...Object.values(families).map(f=>f.module),'src/model-codec.js','src/model-resources.js'])await visit(file);
 const sorted=[...files].sort(),hash=createHash('sha256');for(const file of sorted)hash.update(file+'\0').update(await readFile(file)).update('\0');
 return{files:sorted,sha256:hash.digest('hex')};
}
export async function ensureDetailAssets(){
 const inputs=await detailInputs();let previous;
 try{const source=await readFile(descriptor,'utf8');previous=JSON.parse(source.slice(source.indexOf('{'),source.lastIndexOf('}')+1));}catch{}
 if(previous?.inputsSha256===inputs.sha256){
  let valid=Object.keys(families).every(family=>previous.families?.[family]);
  for(const entry of Object.values(previous.families||{})){try{if(sha256(await readFile('public'+entry.url))!==entry.sha256)valid=false;}catch{valid=false;}}
  if(valid){console.log('Full-precision detail assets are current');return previous;}
 }
 // Generated texture recipes are serialized, with their real pixels rebuilt
 // locally in the browser. No reference images are part of these payloads.
 globalThis.document={createElement:()=>({getContext:()=>({createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)}),putImageData(){},fillRect(){},strokeRect(){},fillText(){}})})};
 const result={format:1,inputsSha256:inputs.sha256,families:{}};
 await mkdir('public/models',{recursive:true});
 for(const [family,entry] of Object.entries(families)){
  const module=await import('../'+entry.module),started=performance.now(),model=module[entry.builder]();
  const constructionMs=performance.now()-started;
  try{
   const audit=auditDetailDelivery(model),compressed=gzipSync(audit.encoded,{level:9}),hash=sha256(compressed);
   const manifest={format:1,family,precision:'native',inputsSha256:inputs.sha256,url:'/models/detail-'+entry.asset+'-'+hash.slice(0,24)+'.bin.gz',sha256:hash,bytes:compressed.byteLength,decodedSha256:sha256(audit.encoded),decodedBytes:audit.encoded.byteLength,triangles:audit.triangles,meshes:audit.meshes,parts:audit.parts,generatedAt:new Date().toISOString(),buildMs:performance.now()-started,validation:audit.validation,timings:{constructionMs,...audit.timings}};
   assertUnchanged(await detailInputs(),inputs);
   let exists=false;try{await stat('public'+manifest.url);exists=true;}catch{}
   if(!exists)await writeFile('public'+manifest.url,compressed,{flag:'wx'});
   else if(sha256(await readFile('public'+manifest.url))!==hash)throw Error('Existing content-addressed detail asset differs; preserved without overwrite');
   result.families[family]=manifest;console.log(JSON.stringify(manifest));
  }finally{disposeModel(model);}
 }
 assertUnchanged(await detailInputs(),inputs);
 await preserveFiles([descriptor],'before-detail-regeneration');
 await writeFile(descriptor,'// Generated by scripts/build-details.mjs; previous assets remain preserved.\nexport default '+JSON.stringify(result,null,2)+';\n');
 return result;
}
function assertUnchanged(actual,expected){if(actual.sha256!==expected.sha256)throw Error('Native detail inputs changed during generation; run again after builders finish');}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))await ensureDetailAssets();
