import {test} from 'node:test';
import assert from 'node:assert/strict';
import {gzipSync} from 'node:zlib';
import * as T from 'three';
import {encodeModel} from '../src/model-codec.js';
import {packNativeContainer,restoredNativeIdentity,inspectNativeContainer,sha256} from './native-model-packing.mjs';
import {parseGeneratedVehicleDescriptor,inspectGeneratedVehicle} from './generated-vehicle-evidence.mjs';
import {disposeModel} from '../src/model-resources.js';

function fixture(){
 const root=new T.Group(),group=new T.Group();group.name='part';root.add(group);
 const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.BufferAttribute(new Float32Array([-0,.123456789,-8,2,0,3,0,4,0]),3));geometry.setIndex([0,1,2]);
 const material=new T.MeshStandardMaterial({polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:2});
 const mesh=new T.Mesh(geometry,material);mesh.userData.partId='part';group.add(mesh);
 const model={root,groups:new Map([['part',group]])};
 const raw=encodeModel(model,{compact:false});disposeModel(model);
 const packed=packNativeContainer(raw),buffer=gzipSync(packed),hash=sha256(buffer);
 const manifest={format:1,precision:'native',compression:'gzip',packing:'delta-byte-plane',url:'/models/vehicle-'+hash.slice(0,24)+'.fiero',sha256:hash,bytes:buffer.length,decodedSha256:sha256(packed),decodedBytes:packed.length,nativeSha256:sha256(raw),nativeBytes:raw.length,inputsSha256:'a'.repeat(64),parts:1,meshes:1,triangles:1,validation:{nativeRoundTrip:true,exactPartBounds:true,nativeProperties:true,configurationCases:57}};
 return{raw,packed,buffer,record:{manifest,descriptor:'fixture'},source:'// Generated by scripts/build-vehicle.mjs; previous assets remain preserved.\nexport default '+JSON.stringify(manifest)+';'};
}
test('lossless native vehicle delivery retains original float bits, indices and polygon settings',()=>{
 const {raw,packed,buffer,record,source}=fixture();assert.deepEqual(restoredNativeIdentity(packed),{sha256:sha256(raw),bytes:raw.length});
 assert.equal(parseGeneratedVehicleDescriptor(source,'fixture').manifest.sha256,record.manifest.sha256);
 const inspected=inspectGeneratedVehicle(buffer,record);assert.deepEqual(inspected.partIds,['part']);assert.equal(inspected.triangles,1);
 const material=inspectNativeContainer(packed,'delta-byte-plane').metadata.materials[0];assert.equal(material.properties.polygonOffset,true);assert.equal(material.properties.polygonOffsetFactor,-1);assert.equal(material.properties.polygonOffsetUnits,2);
});
test('vehicle distribution refuses corrupt bytes, false native identity and unvalidated descriptors',()=>{
 const {buffer,record,source}=fixture(),corrupt=Buffer.from(buffer);corrupt[corrupt.length-1]^=1;
 assert.throws(()=>inspectGeneratedVehicle(corrupt,record),/compressed hash/);
 assert.throws(()=>inspectGeneratedVehicle(buffer,{...record,manifest:{...record.manifest,nativeSha256:'b'.repeat(64)}}),/native bit patterns/);
 assert.throws(()=>parseGeneratedVehicleDescriptor(source.replace('"nativeProperties":true','"nativeProperties":false'),'bad'),/Missing vehicle validation/);
 assert.throws(()=>parseGeneratedVehicleDescriptor(source.replace('"configurationCases":57','"configurationCases":0'),'bad'),/configuration validation/);
 assert.throws(()=>parseGeneratedVehicleDescriptor(source.replace('"precision":"native"','"precision":"compact"'),'bad'));
});
test('offline native packing refuses quantized input and trailing geometry bytes',()=>{
 const {raw}=fixture();assert.throws(()=>packNativeContainer(Buffer.concat([raw,Buffer.alloc(4)])),/trailing bytes/);
 const {data,start,entries}=inspectNativeContainer(raw,null);assert(entries.length>1);const wrong=Buffer.from(data);wrong[start+entries[1].entry.offset]^=1;
 assert.notEqual(restoredNativeIdentity(packNativeContainer(wrong)).sha256,sha256(raw),'changed native index must change authenticated identity');
 // Compact inputs are a separate delivery contract, never admitted by native packing.
 const root=new T.Group(),group=new T.Group();root.add(group);const mesh=new T.Mesh(new T.BoxGeometry(),new T.MeshStandardMaterial());mesh.userData.partId='part';group.add(mesh);const model={root,groups:new Map([['part',group]])};
 try{assert.throws(()=>packNativeContainer(encodeModel(model,{compact:true})),/Quantized/);}finally{disposeModel(model);}
});
