import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {gzipSync} from 'node:zlib';
import {parseGeneratedDetailDescriptors,inspectGeneratedDetail} from './generated-details-evidence.mjs';

const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const transform={position:[0,0,0],quaternion:[0,0,0,1],scale:[1,1,1],visible:true};
function fixture(change=()=>{}){
 const metadata={version:1,groups:[{id:'part',...transform,meshes:[{...transform,userData:{partId:'part'},material:0,attributes:{position:{offset:0,length:9,type:'Float32Array',itemSize:3,quantization:null,packing:null}},geometryGroups:[{start:0,count:3,materialIndex:0}],drawRange:{start:0,count:null}}]}],materials:[{type:'MeshStandardMaterial'}],textures:[{recipe:{kind:'text'}}]};change(metadata);
 const meta=Buffer.from(JSON.stringify(metadata)),end=12+meta.length,start=end+(4-end%4)%4,decoded=Buffer.alloc(start+36);decoded.write('FIEROV01');decoded.writeUInt32LE(meta.length,8);meta.copy(decoded,12);
 const buffer=gzipSync(decoded),sha256=hash(buffer),inputsSha256='a'.repeat(64),manifest={format:1,family:'body-system',precision:'native',inputsSha256,url:'/models/detail-body-'+sha256.slice(0,24)+'.bin.gz',sha256,bytes:buffer.length,decodedBytes:decoded.length,decodedSha256:hash(decoded),parts:1,meshes:1,triangles:1,validation:{nativeRoundTrip:true,exactPartBounds:true}};
 return{buffer,record:{manifest,descriptor:'fixture'},source:'// Generated by scripts/build-details.mjs; previous assets remain preserved.\nexport default '+JSON.stringify({format:1,inputsSha256,families:{'body-system':manifest}})+';'};
}
test('detail descriptors admit only attributed native body/engine generator outputs',()=>{
 const {source,record}=fixture();assert.equal(parseGeneratedDetailDescriptors(source,'fixture')[0].manifest.sha256,record.manifest.sha256);
 assert.throws(()=>parseGeneratedDetailDescriptors(source.replace('// Generated by scripts/build-details.mjs;','// downloaded;'),'bad'),/Unattributed/);
 assert.throws(()=>parseGeneratedDetailDescriptors(source.replace('"precision":"native"','"precision":"compact"'),'bad'),/native precision/);
 assert.throws(()=>parseGeneratedDetailDescriptors(source.replace('"nativeRoundTrip":true','"nativeRoundTrip":false'),'bad'),/round-trip/);
 assert.throws(()=>parseGeneratedDetailDescriptors(source.replace('/models/detail-body-','/models/imported-'),'bad'),/asset path/);
});
test('native detail payload checks hashes, transforms, face groups and complete inventories',()=>{
 const {buffer,record}=fixture(),result=inspectGeneratedDetail(buffer,record);assert.equal(result.triangles,1);assert.deepEqual(result.partIds,['part']);
 const corrupt=Buffer.from(buffer);corrupt[corrupt.length-1]^=1;assert.throws(()=>inspectGeneratedDetail(corrupt,record),/preserved generator output/);
 assert.throws(()=>inspectGeneratedDetail(buffer,{...record,manifest:{...record.manifest,decodedSha256:'b'.repeat(64)}}),/decoded hash/);
 for(const [change,message]of [
  [m=>m.groups[0].meshes[0].attributes.position.quantization={min:[0,0,0],max:[1,1,1]},/quantized/],
  [m=>m.groups[0].meshes[0].attributes.position.offset=40,/outside payload/],
  [m=>m.groups[0].meshes[0].userData.partId='other',/picking identity/],
  [m=>m.textures[0].recipe.kind='image',/imported texture/],
  [m=>m.groups[0].meshes[0].geometryGroups[0].count=-1,/face group/],
 ]){const bad=fixture(change);assert.throws(()=>inspectGeneratedDetail(bad.buffer,bad.record),message);}
});
