import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {gzipSync} from 'node:zlib';
import {parseGeneratedOverviewDescriptor,inspectGeneratedOverview} from './generated-overview-evidence.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
function fixture(kind='text'){
 const metadata=Buffer.from(JSON.stringify({version:1,groups:[{id:'body',meshes:[{attributes:{position:{length:9,itemSize:3}}}]}],textures:[{recipe:{kind}}]}));
 const decoded=Buffer.alloc(12+metadata.length);decoded.write('FIEROV01');decoded.writeUInt32LE(metadata.length,8);metadata.copy(decoded,12);
 const buffer=gzipSync(decoded),sha256=hash(buffer),manifest={format:1,inputsSha256:'a'.repeat(64),url:'/models/overview-'+sha256.slice(0,24)+'.bin.gz',sha256,bytes:buffer.length,decodedBytes:decoded.length,decodedSha256:hash(decoded),parts:1,meshes:1,triangles:1};
 return{buffer,record:{manifest,descriptor:'fixture'}};
}
test('only an explicitly generated descriptor admits a model payload',()=>{
 const {record:{manifest}}=fixture();const source='// Generated by scripts/build-overview.mjs; preserved\nexport default '+JSON.stringify(manifest)+';';
 assert.equal(parseGeneratedOverviewDescriptor(source,'fixture').manifest.sha256,manifest.sha256);
 assert.throws(()=>parseGeneratedOverviewDescriptor('export default '+JSON.stringify(manifest),'imported'),/Unattributed/);
 assert.throws(()=>parseGeneratedOverviewDescriptor(source.replace(manifest.url,'/models/download.glb'),'wrong-path'),/Unexpected/);
});
test('native payload validates hash, decoded identity, counts and procedural textures',()=>{
 const {buffer,record}=fixture();assert.equal(inspectGeneratedOverview(buffer,record).triangles,1);
 const changed=Buffer.from(buffer);changed[changed.length-1]^=1;assert.throws(()=>inspectGeneratedOverview(changed,record),/preserved generator output/);
 assert.throws(()=>inspectGeneratedOverview(buffer,{...record,manifest:{...record.manifest,triangles:2}}),/triangle inventory/);
 const imported=fixture('image');assert.throws(()=>inspectGeneratedOverview(imported.buffer,imported.record),/imported texture/);
});
