import {exteriorParts} from './exterior-catalog.js';
const cd='https://fieroinfo.com/manuals/84-88_Fiero_Parts_%26_Illustrations_CD.pdf';
const service='https://fieroinfo.com/manuals/1986_Fiero_Service_Manual.pdf';
export const bodySections=[
 {id:'body-system',name:'Body panels & attachment hardware'},
 {id:'body-hood',parent:'body-system',name:'Front hood, hinges & release',spread:[0,.28,-.12]},
 {id:'body-decklid',parent:'body-system',name:'Rear decklid, vents & torque rods',spread:[0,.28,.15]},
 {id:'body-front-panels',parent:'body-system',name:'Front fascia, fenders & liners',spread:[0,.08,-.24]},
 {id:'body-rear-panels',parent:'body-system',name:'Rear fascia, quarters & liners',spread:[0,.08,.24]},
 {id:'body-door-left',parent:'body-system',name:'Driver door & hinge hardware',spread:[.24,.03,0]},
 {id:'body-door-right',parent:'body-system',name:'Passenger door & hinge hardware',spread:[-.24,.03,0]},
 {id:'body-side-panels',parent:'body-system',name:'Rocker covers & retainers',spread:[0,-.10,0]},
 {id:'body-roof',parent:'body-system',name:'Roof, A-pillars & retainers',spread:[0,.38,0]},
 {id:'body-rear-clip',parent:'body-system',name:'Rear roof clip, sails & backlight',spread:[0,.3,.18]},
 {id:'body-glazing',parent:'body-system',name:'Windshield, seals & wipers',spread:[0,.28,-.1]},
];
export const bodyParts=[];
function add(key,section,name,description,spread,vehiclePart,page,callout,extra={}){bodyParts.push({id:'bd-'+key,section,system:'body',name,description,spread,vehiclePart,callout,location:bodySections.find(s=>s.id===section).name,source:page<1000?'GM 22P · 1985 body / panel hardware':'1986 Pontiac service · body hardware',sourceUrl:(page<1000?cd:service)+'#page='+page,referenceNote:'Panel and mechanism identity follows the 1985 application rows, with adjacent-year service figures for attachment relationships. Exterior curves are revised against owner photographs and GM panel illustrations. Local surfaces, hinge axes, fastener coordinates and weatherstrip profiles are reconstructed, not tooling or body-alignment data.',...extra});}
export const bodySurfaceOwners=[
 ...exteriorParts.map(e=>[e.id,e.section,e.name,e.spread,e.page,e.callout]),
 ['hood','body-hood','Hood exterior skin',[0,.22,0],237,1],
 ['decklid','body-decklid','Rear decklid exterior skin',[0,.26,0],343,22],
 ['deck-vent-left','body-decklid','Driver-side engine vent grille',[.08,.20,0],336,53],['deck-vent-right','body-decklid','Passenger-side engine vent grille',[-.08,.20,0],336,2],
 ['nose','body-front-panels','SE front fascia',[0,0,-.22],237,16],['fender-left','body-front-panels','Driver-side front fender',[.22,.05,0],237,7],['fender-right','body-front-panels','Passenger-side front fender',[-.22,.05,0],237,7],
 ['rear-fascia','body-rear-panels','SE rear fascia',[0,0,.22],336,36],['quarter-left','body-rear-panels','Driver-side rear quarter & intake',[.22,.05,0],336,23],['quarter-right','body-rear-panels','Passenger-side rear quarter',[-.22,.05,0],336,23],
 ['door-left','body-door-left','Driver door exterior skin',[.24,0,0],336,25],['door-right','body-door-right','Passenger door exterior skin',[-.24,0,0],336,25],
 ['door-trim-left','body-door-left','Driver door interior trim',[-.16,0,0],1214,7],['door-trim-right','body-door-right','Passenger door interior trim',[.16,0,0],1214,7],
 ['door-glass-left','body-door-left','Driver door glass',[0,.28,0],300,1],['door-glass-right','body-door-right','Passenger door glass',[0,.28,0],300,1],
 ['rocker-left','body-side-panels','Driver-side rocker cover',[.20,-.07,0],336,17],['rocker-right','body-side-panels','Passenger-side rocker cover',[-.20,-.07,0],336,17],
 ['roof','body-roof','Roof skin, A-pillars & roof preview',[0,.21,0],336,38],['rear-clip','body-rear-clip','Rear roof clip & buttresses',[0,.21,.14],336,3],['sail-left','body-rear-clip','Driver-side sail applique',[.20,.08,0],336,24],['sail-right','body-rear-clip','Passenger-side sail applique',[-.20,.08,0],336,24],['rear-window','body-rear-clip','Recessed backlight',[0,.13,-.12],336,39],['glass','body-glazing','Windshield & perimeter seals',[0,.15,-.1],336,null],
];
for(const [owner,section,name,spread,page,callout]of bodySurfaceOwners)add('skin-'+owner,section,name,'Shared with the assembled car. Native curved panel geometry uses the revised reconstructed shape; panel sections, folded returns and local mounting dimensions remain provisional.',spread,owner,page,callout,{surface:true,...(exteriorParts.find(e=>e.id===owner)||{}),id:'bd-skin-'+owner,vehiclePart:owner});
for(const [key,name,description,spread,callout,page]of [
 ['inner','Hood bonded inner reinforcement','Open reinforcing frame follows the outer hood, with headlamp apertures and attachment lands. Bonded separation is an illustrative construction view.',[0,.08,0],1,237],
 ['left-hinge','Driver-side front hood hinge','Separate body foot, rotating strap and pin at the front edge.',[.12,-.08,0],21,1208],['right-hinge','Passenger-side front hood hinge','Opposite front hinge, sharing the hood’s forward axis.',[-.12,-.08,0],21,1208],['hinge-bolts','Hood-to-hinge bolt set','Four grouped bolts at the two hinge straps.',[0,-.17,-.08],22,1208],['hinge-nuts','Hood hinge-to-body nuts','Separate grouped body attachment nuts.',[0,-.25,-.08],23,1208],
 ['stay','Mechanical hood hold-open stay','Slotted steel support with a sliding inner member and attachment plates, shown in its closed pose. No gas strut is substituted.',[-.18,-.08,0],18,1208],['stay-bolts','Hood stay upper bolts','Separate pair of upper support bolts.',[-.25,.10,0],19,1208],['stay-nuts','Hood stay lower nuts','Separate pair of lower support nuts.',[-.25,-.16,0],20,1208],
 ['latch','Hood latch','Open stamped latch housing, catch and return spring at the rear cowl edge.',[0,-.12,.13],24,1209],['latch-bolts','Hood latch body bolts','Two separate latch attachment bolts, grouped as a pair.',[0,-.21,.13],25,1209],['striker','Hood striker plate','Folded striker attached to the underside of the hood.',[0,.11,.12],27,1209],['striker-nuts','Hood striker nuts','Separate retaining nut pair.',[0,.21,.12],28,1209],['release-cable','Hood release cable & connector','Driver-side release route, outer sheath and connector at the latch. Exact cable routing remains provisional.',[.16,-.12,.10],26,1209],['seal','Front compartment weatherstrip','Continuous raised sealing lip around the front storage aperture. Cross section is illustrative.',[0,.17,0],43,237],['bumpers','Front hood locating bumpers','Separate adjustable rubber stop pair with threaded stems.',[0,-.08,.08],40,237],
])add('hood-'+key,'body-hood',name,description,spread,'hood',page,callout);
for(const [key,name,description,spread,callout,page]of [
 ['inner','Decklid bonded inner reinforcement','Open reinforcing frame beneath the notchback decklid. The bonded skin is separated for construction inspection.',[0,.10,0],22,343],['left-hinge','Driver-side rear decklid hinge','Formed body bracket and bent lid arm with pin and torque-rod connection.',[.16,-.04,0],13,343],['right-hinge','Passenger-side rear decklid hinge','Separate opposite hinge at the forward edge of the decklid.',[-.16,-.04,0],13,343],['lid-bolts','Decklid hinge-to-lid bolts','Four grouped bolts at the lid arms.',[0,.20,-.05],1,1248],['body-nuts','Decklid hinge-to-body nuts','Separate body attachment nuts.',[0,-.19,-.07],5,1248],
 ['left-rod','Driver-side decklid torque rod','Bent spring-steel rod crossing the forward engine compartment. Exact diameter, preload and option-specific spring choice are unverified.',[.10,-.10,-.10],11,343],['right-rod','Passenger-side decklid torque rod','Second crossed torque rod, with an independent hinge connection.',[-.10,-.16,-.10],11,343],['rod-hooks','Decklid torque-rod retaining hooks','Separate body-mounted hook pair.',[0,-.24,-.12],7,1249],['rod-pins','Torque-rod retaining pins','Separate retaining pin pair. Position is illustrative, not a tension setting.',[0,-.29,-.12],9,1249],['rod-sleeves','Torque-rod isolation sleeves','Short sleeves at the crossed rod sections.',[0,-.20,-.18],11,343],
 ['latch','Rear decklid latch','Stamped housing, rotary catch and lever at the rear underside of the lid.',[0,-.12,.12],17,1251],['latch-bolts','Rear latch attachment bolts','Separate latch-to-lid fasteners.',[0,-.20,.13],18,1251],['striker','Rear compartment striker','Body-mounted folded striker and its loop.',[0,-.21,.08],15,1250],['striker-bolts','Rear striker retaining bolts','Grouped body attachment bolts.',[0,-.30,.08],16,1250],['lock-cylinder','Rear decklid lock cylinder','Key barrel and drive end beneath the existing outer lock face. Internal tumblers remain grouped.',[0,.16,.15],19,1251],['lock-seal','Decklid lock-cylinder gasket','Independent annular gasket beneath the lock face.',[0,.23,.15],20,1251],['lock-retainer','Decklid lock-cylinder retainer','Open spring retainer around the barrel.',[.12,.02,.12],21,1251],['lock-screws','Decklid lock-retainer screws','Separate retainer screw pair.',[.12,-.08,.12],22,1251],['lock-shaft','Decklid lock drive shaft','Bent connecting shaft between barrel and latch.',[-.12,-.04,.12],23,343],['trunk-seal','Rear compartment weatherstrip','Continuous rounded lip following the rear trunk opening, distinct from the engine lid leading-edge seal.',[0,.20,.05],3,343],['bumpers','Rear decklid bump stops','Separate rubber stop pair with threaded stems.',[0,-.08,.12],17,343],
])add('deck-'+key,'body-decklid',name,description,spread,'decklid',page,callout);
for(const [side,s]of [['left',1],['right',-1]]){
 add('vent-'+side+'-retainer','body-decklid',(s>0?'Driver':'Passenger')+' vent support & retainer','Early removable grille support and attachment lands. Local profiles remain reconstructed.',[s*.14,-.10,0],'deck-vent-'+side,336,40);
 add('vent-'+side+'-fasteners','body-decklid',(s>0?'Driver':'Passenger')+' vent fastener set','Grille captive fasteners, washers and bumpers grouped for inspection.',[s*.14,.17,0],'deck-vent-'+side,336,s>0?51:48);
 const where='body-door-'+side,owner='door-'+side,word=s>0?'Driver':'Passenger';
 for(const [key,name,callout,spread]of [
 ['upper-body','upper body hinge strap',43,[s*.03,.10,-.10]],['upper-door','upper door hinge strap',45,[s*.12,.10,0]],['upper-pin','upper hinge pin',47,[s*.08,.24,0]],
 ['lower-body','lower body hinge strap',41,[s*.03,-.05,-.10]],['lower-door','lower door hinge strap',42,[s*.12,-.05,0]],['lower-pin','lower hinge pin',47,[s*.08,.09,0]],['hinge-spring','lower hinge spring',44,[s*.17,-.04,-.06]],['hinge-bolts','hinge attachment bolts',46,[s*.24,0,-.10]],
 ['latch','door latch',10,[s*.13,0,.08]],['striker','door striker & washer',20,[-s*.06,0,.15]],['handle-rod','outside-handle latch rod',6,[s*.16,.06,.03]],['lock-rod','key-cylinder lock rod',5,[s*.20,.08,.03]],
 ['inner-frame','door inner reinforcement',null,[-s*.03,0,0]],['seal','door opening weatherstrip',null,[-s*.13,.05,0]],['trim-retainers','door trim retaining clips',8,[-s*.24,0,0]],
 ])add('door-'+side+'-'+key,where,word+' '+name,'Separate factory-referenced component. Local shape and mounting coordinates are reconstructed; this static assembly does not validate latch engagement or door travel.',spread,owner,key==='trim-retainers'?1214:300,callout);
 for(const [front,section,owner,z]of [[true,'body-front-panels','fender-'+side,-1.1865],[false,'body-rear-panels','quarter-'+side,1.1865]]){
  add((front?'front':'rear')+'-liner-'+side,section,word+(front?' front':' rear')+' wheelhouse liner','Curved inner wheelhouse shell with an open wheel aperture, independently separated from the painted panel.',[s*.10,-.08,0],owner,front?237:336,front?4:10);
  add((front?'front':'rear')+'-panel-fasteners-'+side,section,word+(front?' front fender':' rear quarter')+' retaining hardware','Grouped panel clips and attachment fasteners. Individual lengths and the complete retainer inventory remain unverified.',[s*.30,.09,0],owner,front?237:336,front?6:11);
 }
 add('rocker-'+side+'-retainers','body-side-panels',word+' rocker retaining strip & clips','Inner retaining strip and separate push-in fastener geometry along the rocker cover.',[s*.10,.07,0],'rocker-'+side,336,14);
}
for(const [key,name,spread,owner,page,callout]of [
 ['front-fascia-retainers','Front fascia retaining strip & fasteners',[0,.13,-.12],'nose',237,3],['rear-fascia-retainers','Rear fascia retaining strip & fasteners',[0,.13,.12],'rear-fascia',336,37],['roof-fasteners','Front roof attachment bolts',[0,-.10,0],'roof',336,38],['clip-side-bolts','Rear roof clip side and frame bolts',[0,-.14,.12],'rear-clip',336,3],['clip-roof-nuts','Rear roof clip roof nuts',[0,-.10,-.1],'rear-clip',336,3],['clip-pillar-bolts','Rear roof clip pillar bolts',[0,-.20,0],'rear-clip',336,3],['clip-fuel-pocket-bolts','Rear roof clip fuel-pocket bolts',[.13,-.10,0],'rear-clip',336,9],
])add(key,key.startsWith('front-fascia')?'body-front-panels':key.startsWith('rear-fascia')?'body-rear-panels':key==='roof-fasteners'?'body-roof':'body-rear-clip',name,'Separate attachment set. Rear roof fastener grouping also follows the publicly available 1985 service sample, printed 6-9, Fig. 6-15; exact mounting coordinates remain provisional.',spread,owner,page,callout);
