// Local comparison workspace: shares production geometry; omits concealed
// service assemblies and uses a simple lighting rig to make shape review fast.
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {parts} from './data.js';
import {createMaterials} from './materials.js';
import {geometryTools} from './geometry.js';
import {buildVehicleBodyHardware} from './vehicle-body-hardware.js';
import {buildBody} from './body.js';
import {buildMechanics,buildInterior} from './mechanics.js';
import {buildVehicleLighting} from './lighting-detail.js';
import {buildVehicleHeadlights} from './headlight-detail.js';
import {buildVehicleExhaust} from './vehicle-exhaust.js';
import {correctLegacyHandedness} from './vehicle-frame.js';
import {defaultConfiguration} from './configuration.js';
const host=document.querySelector('#model'),renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(1);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;host.append(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#d5d7d5');const pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;scene.environmentIntensity=.5;
scene.add(new T.HemisphereLight('#fff9ef','#777e82',1.2));const key=new T.DirectionalLight('#fff7ec',2);key.position.set(4,7,-3);scene.add(key);
const root=new T.Group(),groups=new Map();for(const p of parts){const g=new T.Group();groups.set(p.id,g);root.add(g);}const mats=createMaterials(),h=geometryTools(groups,mats);
buildBody(h);buildMechanics(h);buildVehicleBodyHardware(groups,mats);buildInterior(h);buildVehicleLighting(groups,mats);buildVehicleHeadlights(groups,mats);buildVehicleExhaust(groups,mats);h.optimize();correctLegacyHandedness(groups);
const config={...defaultConfiguration,roof:'glass',deck:'rack',headlights:true};
const visibleSystems=new Set(['body','interior']);for(const p of parts){const g=groups.get(p.id);g.visible=visibleSystems.has(p.system)||['wheels','tyres','tires','headlights','taillights','front-signals','marker-lamps','license-lamps','exhaust'].includes(p.id);g.traverse(m=>{if(!m.isMesh)return;m.visible=!m.userData.option||config[m.userData.option]===m.userData.value;});}
// Use the same alpha-glazing fallback as the manual on software renderers.
const gl=renderer.getContext(),debugInfo=gl.getExtension('WEBGL_debug_renderer_info');
if(debugInfo&&/SwiftShader|llvmpipe|Software/i.test(gl.getParameter(debugInfo.UNMASKED_RENDERER_WEBGL)))root.traverse(m=>{
 if(!m.isMesh||!m.material.transmission)return;
 m.material.transmission=0;m.material.transparent=true;m.material.opacity=m.userData.materialName==='glass'?.22:.30;m.material.depthWrite=false;m.material.needsUpdate=true;
});
scene.add(root);const floor=new T.Mesh(new T.PlaneGeometry(30,30),new T.MeshBasicMaterial({color:'#d5d7d5'}));floor.rotation.x=-Math.PI/2;floor.position.y=-.006;scene.add(floor);
const perspectiveCamera=new T.PerspectiveCamera(35,1,.05,60),orthographicCamera=new T.OrthographicCamera(-1,1,1,-1,.05,60);let camera=perspectiveCamera;const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.62,0);controls.enableDamping=false;
const views={driverElevation:{camera:[-7,.62,0],target:[0,.62,0],ortho:true,photo:'IMG_5459.jpg'},passengerElevation:{camera:[7,.62,0],target:[0,.62,0],ortho:true,photo:'IMG_5459.jpg'},frontElevation:{camera:[0,.68,-7],target:[0,.68,0],ortho:true,width:2.35,photo:'IMG_5462.jpg'},rearElevation:{camera:[0,.68,7],target:[0,.68,0],ortho:true,width:2.35,photo:'IMG_5461.jpg'},plan:{camera:[0,7,0],target:[0,0,0],ortho:true,width:5.25,photo:'IMG_5461.jpg'},rear:{camera:[3.7,1.65,4.94],offset:.02,photo:'IMG_5461.jpg'},side:{camera:[7,1.15,1.2],offset:.13,photo:'IMG_5459.jpg'},front:{camera:[4.5,1.7,-5.0],offset:.02,photo:'IMG_5462.jpg'},straightRear:{camera:[0,1.1,5.5],offset:0,photo:'IMG_5461.jpg'},frontWheel:{camera:[2.0,.55,-1.1865],target:[.80,.307,-1.1865],offset:0,photo:'IMG_5459.jpg'},roof:{camera:[2.0,2.3,-.2],target:[0,1.0,.15],offset:0,photo:'IMG_5461.jpg'},frontClose:{camera:[1.8,1.2,-3.2],target:[0,.68,-1.10],offset:0,photo:'IMG_5462.jpg'}};
Object.assign(views,{driverWindow:{camera:[-4,1,-.07],target:[-.65,1,-.07],ortho:true,width:1.7,photo:'IMG_5459.jpg'},passengerWindow:{camera:[4,1,-.07],target:[.65,1,-.07],ortho:true,width:1.7,photo:'IMG_5459.jpg'},windowCorner:{camera:[-2.7,1.7,-1.1],target:[-.55,1,-.02],photo:'IMG_5459.jpg'},windshield:{camera:[0,1.55,-3.2],target:[0,1,-.45],photo:'IMG_5462.jpg'},backlight:{camera:[0,1.4,2.6],target:[0,1,.70],photo:'IMG_5461.jpg'},sunroofClose:{camera:[0,4,.18],target:[0,1.18,.18],ortho:true,width:1.45,photo:'IMG_5461.jpg'}});
Object.assign(views,{pillarProfile:{camera:[-4,1,.19],target:[-.65,1,.19],ortho:true,width:2.10,photo:'IMG_5459.jpg'},rearProfile:{camera:[-4,.57,1.55],target:[-.65,.57,1.55],ortho:true,width:1.2,photo:'IMG_5459.jpg'}});
Object.assign(views,{deckVents:{camera:[-1.4,2.5,1.6],target:[0,.85,1.02],ortho:true,width:1.65,photo:'IMG_5461.jpg'},molding:{camera:[-4,.61,.90],target:[-.82,.61,.90],ortho:true,width:2.05,photo:'IMG_5459.jpg'}});
const references={grilles:'/references/1985-gt-original-engine-bay-r12.jpg',looseGrille:'/references/notchback-vent-original-r12.jpg',catalog:'/references/pontiac-1985-full-line-12-r11.jpg',structure:'/references/pontiac-1985-full-line-13-r11.jpg',profile:'/artifacts/body-reference-r7/production-profile-detail.png',cad:'/references/gm-1984-cad-profile-r11.png'};let currentPhoto='IMG_5461.jpg';
function reference(){const value=document.querySelector('#reference').value;document.querySelector('#photo').src=references[value]||'/references/owner-body-review/'+currentPhoto;document.querySelector('#photo').alt=value==='owner'?'Owner photograph':'Original Pontiac publication reference';}
document.querySelector('#reference').onchange=reference;
let queued=false;function render(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;renderer.render(scene,camera);});}let viewWidth=4.6;function resize(){renderer.setSize(host.clientWidth,host.clientHeight);const aspect=host.clientWidth/host.clientHeight;if(camera.isOrthographicCamera){camera.left=-viewWidth/2;camera.right=viewWidth/2;camera.top=viewWidth/aspect/2;camera.bottom=-camera.top;}else camera.aspect=aspect;camera.updateProjectionMatrix();render();}
function view(name){const v=views[name];camera=v.ortho?orthographicCamera:perspectiveCamera;controls.object=camera;camera.up.set(0,1,0);if(['plan','sunroofClose'].includes(name))camera.up.set(0,0,-1);viewWidth=v.width||4.6;camera.position.set(...v.camera);if(!v.ortho)camera.setViewOffset(host.clientWidth,host.clientHeight,0,-host.clientHeight*(v.offset||0),host.clientWidth,host.clientHeight);resize();controls.target.set(...(v.target||[0,.62,0]));controls.update();currentPhoto=v.photo;reference();render();}
controls.addEventListener('change',render);new ResizeObserver(resize).observe(host);
document.querySelector('#clay').addEventListener('change',e=>{root.traverse(m=>{if(!m.isMesh||m.userData.materialName!=='red')return;m.userData.reviewOriginal??=m.material;m.userData.reviewClay??=new T.MeshStandardMaterial({color:'#a8aeaa',roughness:.8,side:T.DoubleSide});m.material=e.target.checked?m.userData.reviewClay:m.userData.reviewOriginal;});render();});
for(const name of Object.keys(views)){const b=document.createElement('button');b.textContent={driverElevation:'Driver elevation',passengerElevation:'Passenger elevation',frontElevation:'Front elevation',rearElevation:'Rear elevation',plan:'Plan view',rear:'Rear quarter',side:'Side profile',front:'Front quarter',straightRear:'Straight rear',frontWheel:'Wheel detail',roof:'Roof and glazing',frontClose:'Hood and nose',driverWindow:'Driver window',passengerWindow:'Passenger window',windowCorner:'Window corner',windshield:'Windshield seals',backlight:'Rear-window seal',sunroofClose:'Sunroof seal',pillarProfile:'Pillar profile',rearProfile:'Rear bumper profile',deckVents:'Engine grilles',molding:'Side moldings'}[name];b.dataset.reviewView=name;b.onclick=()=>view(name);document.querySelector('#views').append(b);}
for(const [key,label,options]of [['windows','Side glass',[['closed','Closed'],['open','Lowered']]],['roof','Roof panel',[['glass','Glass'],['removed','Removed'],['solid','Solid']]]]){const l=document.createElement('label');l.textContent=label+' ';const select=document.createElement('select');select.id='review-'+key;select.setAttribute('aria-label',label);for(const [value,text]of options){const o=document.createElement('option');o.value=value;o.textContent=text;select.append(o);}select.value=config[key];select.onchange=()=>{config[key]=select.value;root.traverse(m=>{if(m.isMesh&&m.userData.option===key)m.visible=m.userData.value===config[key];});render();};l.append(select);document.querySelector('#views').append(l);}
window.__bodyReview={view,render,groups,projection:()=>camera.type,bounds:id=>{root.updateMatrixWorld(true);const b=new T.Box3();groups.get(id).traverseVisible(m=>{if(m.isMesh)b.expandByObject(m);});return{min:b.min.toArray(),max:b.max.toArray()};}};resize();view('rear');renderer.domElement.dataset.ready='true';
