export const chargingSource='https://fieroinfo.com/manuals/84-88_Fiero_Parts_%26_Illustrations_CD.pdf';
export const chargingSections=[
 {id:'charging-system',name:'Battery, starter & alternator'},
 {id:'charging-battery',parent:'charging-system',name:'Side-terminal battery, tray & cables'},
 {id:'charging-starter',parent:'charging-system',name:'Delco starter & solenoid'},
 {id:'charging-alternator',parent:'charging-system',name:'1985–87 generator & bracket'},
];
export const chargingParts=[];
function part(section,key,name,description,spread,callout=null,page=67){chargingParts.push({id:'ch-'+key,section:'charging-'+section,system:'electrical',name,description,spread,callout,source:'GM 22P · '+(section==='battery'?'battery mounting':section==='starter'?'starter construction':'1984–87 generator'),sourceUrl:chargingSource+'#page='+page,location:chargingSections.find(s=>s.id==='charging-'+section).name,referenceNote:'Catalog drawings establish components and application families. Local dimensions, windings, castings, contact geometry, clearance and cable bends are reconstructed. The installed alternator rating and original starter stamping are not established by the VIN. Internal separation illustrates construction, not an approved service sequence.'});}
for(const [key,name,desc,spread,callout]of[
 ['battery-case','Delco Freedom battery case','Original-style maintenance-free rectangular case with side-terminal wells and molded base hold-down ledges.',[0,0,0],4],
 ['battery-lid','Maintenance-free battery lid','Bonded top with vent labyrinth and recessed indicator. No removable flooded-battery filler caps or top terminal posts are substituted.',[0,.17,0],4],
 ['battery-terminals','Two recessed side terminals','Separate lead terminal inserts and insulated side wells.',[0,.04,.13],4],
 ['battery-indicator','Battery charge indicator window','Small integrated hydrometer window in the top. The visual state is illustrative.',[.08,.19,0],4],
 ['battery-tray','Stamped battery tray','Open flanged tray under the passenger-side battery, with drainage openings.',[0,-.16,0],10],
 ['battery-retainer','Lower hold-down wedge','Separate lower retention block at the battery ledge.',[.13,-.03,.10],6],
 ['battery-retainer-bolt','Battery hold-down bolt','Long retainer bolt, separate from the terminal cable bolts.',[.13,.15,.10],5],
 ['battery-heat-shield','Battery heat shield','Formed shield between the battery and hot engine components, with access clearance at the side terminals.',[.17,0,-.10],3],
 ['battery-shield-screws','Heat-shield screws','Separate shield attachment screws.',[.19,.11,-.10],2],
 ['battery-support','Retainer support bracket','Formed support below the hold-down, attached to the tray area.',[0,-.24,.10],9],
 ['positive-cable','Positive battery cable & terminal bolt','Side-terminal positive lead to the starter battery stud. GM lists a 35-inch L44 cable; the visible bends are reconstructed.',[-.15,.04,.12],1],
 ['negative-cable','Negative battery cable & terminal bolt','Side-terminal negative lead to the engine ground with body-ground branch. Catalog lists a 25-inch L44 negative cable; exact routing is unverified.',[.15,.04,-.12],7],
 ['ground-strap','Engine-to-body ground strap','Braided engine/body bond and eyelets. The local path remains a reference reconstruction.',[.14,.10,.12],null],
])part('battery',key,name,desc,spread,callout);
for(const [key,name,desc,spread,callout]of[
 ['starter-yoke','Starter field frame','Open cylindrical steel field frame with pole shoes; original field construction requires the motor stamping for exact selection.',[0,-.16,0],25],
 ['starter-field','Field coils & pole shoes','Separate pole shoes, insulated copper field loops and internal field-to-brush lead. Turn count is illustrative.',[0,0,-.16],25],
 ['starter-armature','Starter armature & shaft','Laminated stack, copper windings, segmented commutator and extended drive shaft.',[.20,0,0],19],
 ['starter-brushes','Four starter brushes','Four independent carbon brush blocks with flexible copper pigtails.',[-.10,.12,0],28],
 ['starter-carrier','Brush carrier & insulation','Open carrier ring and four insulated brush guides.',[.25,0,0],26],
 ['starter-brush-springs','Brush springs & screws','Separate spring fingers and brush-holder fasteners.',[.28,.10,0],27],
 ['starter-end','Commutator end frame','Separate end plate with shaft bearing and through-bolt holes.',[.34,0,0],30],
 ['starter-through-bolts','Starter through-bolts','Two long through-bolts retaining the motor frame and end plate.',[.40,.08,0],31],
 ['starter-nose','Drive-end housing','Cast open nose exposing the pinion engagement region and mounting pad.',[-.21,0,0],9],
 ['starter-bushings','Drive / armature bushings','Separate bronze shaft support bushings.',[-.24,-.10,0],11],
 ['starter-drive','Overrunning drive & pinion','Clutch body and external engagement pinion. Tooth form/count are a reconstruction, not verified mesh data.',[-.15,-.13,0],15],
 ['starter-drive-spring','Drive return spring','Separate coil spring around the drive sleeve.',[-.25,-.13,0],16],
 ['starter-retainers','Drive stops, rings & washers','Separate stop collar, snap rings, washer and locking wire at the drive end.',[-.32,-.13,0],12],
 ['starter-fork','Shift fork & pivot pin','Fork follows the drive collar and connects to the solenoid plunger; pivot is separate.',[-.13,.10,0],7],
 ['solenoid-case','Solenoid shell & windings','Steel shell, insulated pull/hold winding envelopes and rear mounting flange.',[0,.18,0],2],
 ['solenoid-plunger','Solenoid plunger & linkage','Sliding iron plunger with the fork engagement end.',[-.16,.19,0],5],
 ['solenoid-return','Solenoid return spring','Separate return spring around the plunger.',[-.21,.24,0],4],
 ['solenoid-contact','Solenoid moving contact & pushrod','Copper contact disc, insulating pushrod and terminal contact faces.',[.19,.17,0],3],
 ['solenoid-cap','Solenoid terminal cap','Insulated cap with separate large battery/motor studs and smaller control terminal.',[.26,.20,0],2],
 ['solenoid-fasteners','Solenoid mounting screws','Two screws through the solenoid flange into the starter nose.',[.06,.28,0],22],
 ['starter-mount-bolts','Starter mounting bolts & shim preview','Mounting bolts at the cast nose pad. Shim presence/thickness must be verified for the installed motor; the thin interface plate is illustrative.',[-.16,-.24,0],null],
 ['starter-leads','Starter control lead & field strap','Small solenoid control lead and the motor-side field connection, separate from the battery positive cable.',[.20,.24,.12],null],
])part('starter',key,name,desc,spread,callout,56);
for(const [key,name,desc,spread,callout]of[
 ['alt-front','Generator drive-end frame','Cast front frame with open cooling windows, central bearing seat, adjustment ear and pivot lug.',[-.16,0,0],10],
 ['alt-rear','Generator slip-ring-end frame','Separate vented rear casting with brush / regulator openings and output-stud insulation.',[.18,0,0],25],
 ['alt-stator','Stator stack & three-phase windings','Laminated outer stack and three interleaved copper winding groups. Slot and turn counts are illustrative.',[0,.18,0],2],
 ['alt-rotor','Claw-pole rotor & shaft','Interleaved claw pole halves surrounding the field winding, supported by the main shaft.',[0,-.14,0],1],
 ['alt-field','Rotor field winding','Separate insulated field coil inside the two claw-pole halves.',[.09,-.18,0],1],
 ['alt-slip-rings','Rotor slip rings','Two insulated copper rings at the rear shaft, separate from the rotor body.',[.13,-.17,0],1],
 ['alt-front-bearing','Drive-end bearing','Separate races, rolling elements and cage.',[-.24,-.07,0],12],
 ['alt-rear-bearing','Slip-ring-end bearing','Rear shaft bearing and seal.',[.24,-.07,0],23],
 ['alt-bearing-retainer','Front bearing retainer & screws','Open retaining plate and three screws at the drive-end bearing.',[-.26,.08,0],14],
 ['alt-collars','Rotor spacers, slinger & seals','Separate shaft collars, grease slinger and sealing pieces.',[-.30,-.09,0],9],
 ['alt-fan','External generator cooling fan','Formed radial cooling fan ahead of the drive-end frame; blade profile is reconstructed.',[-.31,.08,0],5],
 ['alt-pulley','Generator belt pulley','Grooved steel pulley, separate from the fan and retaining hardware.',[-.40,0,0],6],
 ['alt-pulley-nut','Pulley nut & spring washer','Hex retaining nut and spring washer on the shaft.',[-.46,0,0],7],
 ['alt-regulator','Internal voltage regulator','Potted regulator module with separate mounting tabs and terminal lands.',[.25,.13,0],26],
 ['alt-rectifier','Rectifier bridge & heat sink','Insulated heat-sink segments and six representative rectifier diodes.',[.26,-.13,0],19],
 ['alt-diode-trio','Diode trio','Three excitation diode branches on an insulated carrier.',[.29,.03,.12],20],
 ['alt-brush-holder','Generator brush holder','Insulated holder with two open brush channels.',[.24,.02,-.12],30],
 ['alt-brushes','Two alternator brushes & springs','Separate carbon contacts and compression springs at the slip rings.',[.30,.08,-.13],29],
 ['alt-capacitor','Noise-suppression capacitor','Cylindrical capacitor and connecting terminal.',[.25,-.04,.16],4],
 ['alt-output','B+ output stud & insulating bushings','Separate output terminal, insulating bushings, washer and nut.',[.36,-.05,0],24],
 ['alt-plug','Regulator plug & charging leads','Two-cavity regulator connector, B+ cable and short branch. Pin assignments and full harness routing remain unverified.',[.33,.14,.13],null],
 ['alt-through-bolts','Generator through-bolts','Four long case bolts joining the two frames.',[.39,.10,0],21],
 ['alt-bracket','L44 generator mounting bracket','Open cast accessory bracket with pivot bore and curved adjustment slot; GM 10044919 application.',[-.03,.17,.14],1],
 ['alt-adjust-bolt','Generator adjustment bolt & washer','Separate adjustment bolt at the slotted bracket.',[-.15,.22,.12],4],
 ['alt-pivot-bolt','Generator pivot bolt & bushing','Long pivot bolt and spacer through the bracket and frame lug.',[-.15,-.20,.10],3],
 ['alt-heat-shield','Generator heat shield','Separate shield at the rear of the generator, GM 10036230 in the L44 mounting illustration.',[.39,0,0],9],
 ['alt-bracket-bolts','Generator bracket-to-engine bolts','Bracket attaching bolt set and support hardware; exact installed fastener count remains to verify.',[.06,.24,.18],2],
])part('alternator',key,name,desc,spread,callout,key.includes('bracket')||['alt-adjust-bolt','alt-pivot-bolt','alt-heat-shield'].includes(key)?61:58);
