// An audit of known gaps, not a claim to have enumerated the complete BOM.
export const coverageAudit=[
 {system:'Headlights',modeled:'Separate LH/RH lamps, glass/reflector construction, aiming hardware, spring-loaded covers, buckets, lift links, early motor internals, four individual cushions per gear, two actuator relays, isolation relay and separate driver/column lighting controls. Both endpoint poses share the whole-car geometry; bulb centers use the 1985 nominal 709 mm height and 511 mm lateral offset, with a constant-length reconstructed operating link.',remaining:'Measured dimensions, optical tooling, gear ratios, detailed contact form, calibrated travel, exact harness circuits and validated aiming/diagnostic procedures.'},
 {system:'Body & chassis',modeled:'Expanded body selections: revised skins and glazing, independent exterior trim, mirrors, handles, fuel door, intake, antenna, wipers and roof/deck options with separate sunroof hinges, latch, trim and fasteners, separate rocker covers/door trim/side glass, hood stay/release, decklid torque rods/lock, door hinges/latches, liners, seals and panel retaining sets; existing headlamp mechanisms and space frame.',remaining:'Measured panel sections and body datums, window regulators, full lock and option-specific release internals, exact weatherstrip profiles, complete fastener inventory and structural stampings.'},
 {system:'Engine & intake',modeled:'Block and rotating parts, individual valve gear with stamped rockers and separate retaining hardware, intake, twelve-selection oil-pump/pickup construction with separate gears and relief parts, oil system, dipstick, early oil-pressure sender, timing seals/guide, sensors, fuel tubes, PCV and EGR.',remaining:'Measured castings, all oil/coolant passages, complete gasket and fastener inventory, exact exhaust interfaces and accessory internals.'},
 {system:'Ignition & electrical',modeled:'Detailed distributor stack, ICM, pickup, remote coil, plugs, HT leads, primary/EST leads and tach filter; 108 lamp entries, 62 charging/starting selections and 99 wiring/instrument selections including the original 1985 cluster, 17-position fuse panel, ECM, flashers and junction.',remaining:'Exact factory HT lead routes/cap clocking, full vehicle loom, remaining switches/horn units and installed distributor variant. Cylinder identities and EST circuit assignments have primary references.'},
 {system:'Transmission & clutch',modeled:'Detailed hollow transaxle castings, input/output gear stacks, synchronizers, reverse, bearings, differential, selector, sprung clutch and release gear; separate unequal halfshafts. Nominal 84/23 final-drive teeth and 232/155 mm clutch-facing diameters follow Pontiac 1985 data.',remaining:'Measured involute tooth profiles, individual speed-gear tooth counts and casting dimensions, CV internals, detailed hydraulics and complete mounting hardware.'},
 {system:'Suspension & steering',modeled:'216 selections: formed front/rear arms and frames, ball joints, pivot bushings, separate front shocks and coils, rear strut stacks and toe links, 23 mm front stabilizer, manual rack internals and passenger-side steering damper.',remaining:'Measured frame/arm profiles and pivot coordinates, installed WS6 spring codes and measured coils, original pinion tooth count/ratio, damper internals, steering column joints and verified travel/clearances.'},
 {system:'Brakes & wheels',modeled:'212 brake selections: four separate calipers/pad sets, front integral rotor/hubs and tapered bearings, rear rotors/hub units, parking actuators/cables, composite master, tandem booster, hard lines/hoses and pedal hardware; existing wheel/tire previews and spare.',remaining:'Measured casting contours, rear piston clutch and sealed-hub internals, valve calibration, verified full-travel hose clearance, exact mounting coordinates, tire/wheel surface accuracy and validated repair procedures.'},
 {system:'Cooling & climate',modeled:'Tube-and-fin radiator, tanks, swept fan/shroud/motor, distinct inlet/return pipes and hoses, clamps, recovery tank, shared heater circuit and detailed engine thermostat/pump exteriors. 64 HVAC entries across C41/C60 variants add cases, doors/linkages, cores, blower/resistor/relay, open ducts, controls and optional evaporator/accumulator.',remaining:'Water-pump and fan-motor internals, verified fan variant, measured hose routing, exact C41/C60 case tooling and duct sections, motor/actuator internals and wiring, complete A/C compressor/condenser detail, accumulator internals and refrigerant plumbing.'},
 {system:'Fuel & exhaust',modeled:'53 fuel selections: early stepped tank/cutaway shells, straps and pads, pump/sender/float/strainer, driver filler and vent, separate feed/return, in-line filter, vapor canister and pump relay; engine rails/injectors and cold-start components. 44 exhaust selections add manifolds, crossover/shields, early pellet catalyst cutaway, muffler, tailpipes, clamps and spring hangers.',remaining:'Measured tank/pump geometry and capacity, exact fuel/vapor routing, sender calibration, pump/filter/canister internals, measured exhaust profiles, welded junction interiors, muffler baffles and verified mounting/heat clearances.'},
 {system:'Interior & controls',modeled:'Seats, dashboard, a separate 47-selection original-layout instrument cluster, steering wheel, shifter and pedals.',remaining:'Seat frames/tracks, complete calibrated gauge internals/circuit boards, switch mechanisms, belts, trim attachments and optional accessory hardware.'},
];
