const cd='https://fieroinfo.com/manuals/84-88_Fiero_Parts_%26_Illustrations_CD.pdf';
const service='https://fieroinfo.com/manuals/1986_Fiero_Service_Manual.pdf';
export const exhaustSections=[
 {id:'exhaust-system',name:'1985 V6 exhaust system'},
 {id:'exhaust-manifolds',parent:'exhaust-system',name:'Manifolds & head connections',spread:[0,.18,0]},
 {id:'exhaust-crossover',parent:'exhaust-system',name:'Crossover, shields & spring joint',spread:[.23,.15,0]},
 {id:'exhaust-catalyst',parent:'exhaust-system',name:'Early pellet catalyst & shields',spread:[0,-.12,-.20]},
 {id:'exhaust-rear',parent:'exhaust-system',name:'Muffler, tailpipes & hangers',spread:[0,.06,.24]},
];
export const exhaustParts=[];
function add(key,section,name,description,spread,page,callout){exhaustParts.push({id:'ex-'+key,section,system:'fuel',name,description,spread,callout,location:exhaustSections.find(s=>s.id===section).name,source:page<200?'GM 22P · 1985–86 L44 exhaust':'1986 Pontiac service · exhaust arrangement',sourceUrl:(page<200?cd:service)+'#page='+page,referenceNote:'Catalog application rows identify the early 1985–86 converter, front pipe and muffler. The adjacent-year service figures supply joint, spring and pellet-bed relationships. Local shapes, bends and clearances are reconstructed, not measured fabrication data. Welded-shell separation is a viewing cutaway, not a repair procedure.'});}
for(const [side,word,sign] of [['front','Cabin-side',-1],['rear','Trunk-side',1]]){
 add(side+'-manifold','exhaust-manifolds',word+' exhaust manifold','Three short branches enter a common tubular collector with individual head flanges, weld beads and a two-bolt crossover outlet.',[0,.05,sign*.19],708,side==='front'?5:6);
 add(side+'-gaskets','exhaust-manifolds',word+' manifold gasket set','Three separate port openings with attachment holes, grouped by bank. Exact gasket outline and thickness remain provisional.',[0,.07,sign*.11],708,null);
 add(side+'-bolts','exhaust-manifolds',word+' manifold attachment set','Grouped head attachment bolts and washers. Original stud-versus-bolt allocation remains unverified.',[.10,.10,sign*.28],708,null);
}
for(const [key,name,description,spread,callout] of [
 ['pipe','V6 crossover pipe','Asymmetric crossover joins both manifolds at the driver end of the engine and branches down toward the converter.',[.15,.07,0],17],
 ['front-shield','Forward crossover heat shield','Formed open-backed shield, separate from the pipe.',[.12,.19,-.12],12],['rear-shield','Rearward crossover heat shield','Independent second crossover shield with rolled edges.',[.12,.19,.12],16],
 ['shield-screws','Crossover shield screws & nuts','Separate grouped shield attachment hardware.',[.24,.25,0],13],['manifold-bolts','Crossover-to-manifold bolt sets','Fasteners at the two manifold outlet flanges.',[.27,0,0],11],
 ['seal','Crossover-to-front-pipe seal','Annular graphite-style sealing ring at the spring-loaded joint.',[.15,-.06,-.06],18],['joint-bolts','Front-pipe joint bolt pair','Separate bolts through the two-lug joint.',[.18,-.20,0],20],['joint-springs','Front-pipe joint compression springs','Two independent spring bodies grouped as a pair.',[.24,-.12,0],19],
 ['front-pipe','1985–86 converter front pipe','Early separate downpipe. The later integrated converter/front-pipe application is not substituted.',[.17,-.12,-.06],32],
])add('cross-'+key,'exhaust-crossover',name,description,spread,122,callout);
for(const [key,name,description,spread,callout] of [
 ['wrap','Catalyst outer protective wrap','Pressed outer top wrap with crown ribs and its peripheral seam. Separated only as a cutaway.',[0,.29,0],2],['top-insulation','Catalyst upper insulation','Layer between the outer wrap and converter upper shell. Thickness is illustrative.',[0,.22,0],1],['upper','Converter upper shell','Closed upper chamber with formed inlet/outlet necks. Welded shell separation is a viewing cutaway.',[0,.15,0],3],
 ['pellets','Catalytic pellet bed','Grouped representative pellets identify the factory single-bed construction. Pellet count, composition and bed depth are not calibrated.',[0,.075,0],9],['support','Catalyst bed support','Perforated bed-support sheet; the local perforation pattern is illustrative.',[0,-.07,0],6],['lower-insulation','Catalyst lower insulation','Lower insulating layer, independently selectable in the cutaway.',[0,-.13,0],5],['lower','Converter lower shell','Lower welded chamber with a separate fill-plug opening.',[0,-.21,0],3],['plug','Catalyst fill plug','Separate lower-shell closure from the factory service cutaway. No catalyst service procedure is supplied.',[0,-.29,0],7],
])add('cat-'+key,'exhaust-catalyst',name,description,spread,706,callout);
for(const [key,name,description,spread,callout] of [
 ['floor-shield','Catalyst floor heat shield','Ribbed shield between the converter and floor pan.',[0,.39,-.07],24],['splash-shield','Catalyst lower splash shield','Separate lower shield with exposed mounting ears.',[0,-.37,-.07],21],['shield-clamps','Catalyst shield clamps','Independent shield-to-pipe clamp pair.',[.16,-.31,0],22],['shield-screws','Catalyst shield screws','Grouped shield attachment screws.',[-.16,-.40,0],23],['outlet-clamp','Converter outlet saddle clamp','Catalog nominal 60.32 mm saddle-clamp application, distinct from the smaller tailpipe clamps.',[-.16,-.10,0],25],
])add('cat-'+key,'exhaust-catalyst',name,description,spread,123,callout);
for(const [key,name,description,spread,callout] of [
 ['muffler','Transverse V6 muffler','Oval transverse shell, crimped end seams, inlet and two outlets. Internal tri-flow baffles remain grouped; no unverified chamber geometry is shown.',[0,.16,0],5],['intermediate','Muffler intermediate pipe','Formed pipe from the converter around the passenger side to the muffler. Catalogued with the early muffler; separation here is illustrative.',[-.20,0,0],27],['shield','Muffler-to-trunk heat shield','Pressed shield between the muffler and rear compartment panel.',[0,.29,-.10],3],['shield-screws','Muffler shield attachment screws','Separate grouped shield screws.',[0,.38,-.12],4],
 ['left-tail','Driver-side twin tailpipe','Single formed inlet divides into two outlets. Black SE and bright GT finish previews can be selected in Configure; neither establishes this car’s original tailpipe finish.',[.24,0,.12],10],['right-tail','Passenger-side twin tailpipe','Separate passenger-side pipe and twin outlet assembly.',[-.24,0,.12],1],['tail-clamps','Tailpipe saddle clamp pair','Separate 50.8 mm nominal saddle clamps and nuts at the muffler connections.',[0,-.16,.09],2],['left-hanger','Driver-side tailpipe hanger','Metal body bracket, flexible strap and lower pipe attachment.',[.27,.14,.02],9],['right-hanger','Passenger-side tailpipe hanger','Separate opposite-side bracket and flexible strap.',[-.27,.14,.02],9],['hanger-bolts','Tailpipe hanger bolt set','Grouped body and pipe attachment hardware.',[0,.26,.09],6],['left-fascia-shield','Driver-side fascia heat shield','Early shield above the outlet area; local bends remain reconstructed.',[.26,.29,.12],29],['right-fascia-shield','Passenger-side fascia heat shield','Corresponding opposite-side shield.',[-.26,.29,.12],29],['fascia-nuts','Fascia shield attachment nuts','Separate grouped early shield retaining nuts.',[0,.40,.15],31],['spring-brackets','Muffler spring support brackets','Left and right support brackets at the cradle, with actual attachment holes.',[0,.05,-.20],15],['left-springs','Driver-side muffler support springs','Three hooked tension springs on the driver side, grouped as a set.',[.23,.12,-.10],15],['right-springs','Passenger-side muffler support springs','Three hooked tension springs on the passenger side.',[-.23,.12,-.10],15],
])add('rear-'+key,'exhaust-rear',name,description,spread,122,callout);
