const parts='https://fieroinfo.com/manuals/84-88_Fiero_Parts_%26_Illustrations_CD.pdf';
const service='https://fieroinfo.com/manuals/1986_Fiero_Service_Manual.pdf';
export const fuelSections=[
 {id:'fuel-system',name:'1985 V6 fuel supply & vapor system'},
 {id:'fuel-tank',parent:'fuel-system',name:'Early tank, straps & insulators',spread:[0,-.12,0]},
 {id:'fuel-sender',parent:'fuel-system',name:'In-tank pump & level sender',spread:[0,.25,0]},
 {id:'fuel-filler',parent:'fuel-system',name:'Driver-side filler & vent',spread:[.2,.12,0]},
 {id:'fuel-plumbing',parent:'fuel-system',name:'Feed, return & fuel filter',spread:[-.2,0,.12]},
 {id:'fuel-vapor',parent:'fuel-system',name:'Vapor canister, lines & pump relay',spread:[.18,.15,.1]},
];
export const fuelParts=[];
function add(id,section,name,description,spread,page,callout){fuelParts.push({id:'fu-'+id,section,system:'fuel',name,description,spread,callout,source:page<200?'GM 22P · early L44 fuel / vapor system':'1986 Pontiac service · typical pump and sender',sourceUrl:(page<200?parts:service)+'#page='+page,location:fuelSections.find(s=>s.id===section).name,referenceNote:'The 1985–86 catalog distinguishes the early tank and 1985 sender. Local shapes, dimensions and routing are reconstructed. Pump/sender detail is also informed by an explicitly typical adjacent-year service drawing. No pressure, resistance calibration, running clearance or repair procedure is certified.'});}
for(const [key,name,desc,spread,callout] of [
 ['upper','Tank upper welded shell','Raised rear sender area, lower forward crown, pressed ribs, seam flange and actual sender aperture. This welded shell is separated only to inspect the tank interior.',[0,.24,0],11],
 ['lower','Tank lower welded shell','Shallow formed lower shell with peripheral weld flange. Shell separation is an illustrative cutaway, not a service removal step.',[0,-.18,0],11],
 ['front-strap','Front fuel-tank strap','Curved steel retaining strap across the early tank.',[0,-.24,-.1],15],['rear-strap','Rear fuel-tank strap','Separate rear strap, with attachment ears.',[0,-.24,.1],12],
 ['strap-bolts','Tank strap T-bolts','Separate strap attachment bolt pair.',[.15,-.20,0],13],['strap-nuts','Tank strap nuts','Separate retaining nuts.',[-.15,-.26,0],16],
 ['top-pads','Tank upper anti-squeak pads','Pads between the tank crown and tunnel structure.',[0,.32,0],8],['side-pads','Tank side anti-squeak pads','Side pads along the early tank seam.',[.19,0,0],10],
 ['reinforcement','Floor-pan tank reinforcement','Pressed transverse reinforcement below the tank.',[0,-.32,0],18],['reinforcement-bolts','Tank reinforcement bolts & washers','Separate floor attachment fasteners.',[.18,-.36,0],19],
])add('tank-'+key,'fuel-tank',name,desc,spread,79,callout);
for(const [key,name,description,spread,page,callout] of [
 ['plate','Sender flange & support tubes','Flange, electrical feed-through and formed feed/return/vapor pipes. The 1985 catalog sender is distinct from 1986.',[0,.16,0],79,6],
 ['lock-ring','Sender locking cam ring','Three-lug cam retainer around the sender flange.',[0,.27,0],79,4],['gasket','Sender flange sealing ring','Independent tank-to-sender gasket.',[.12,.12,0],79,7],
 ['separator','Sender splash cup','Upper liquid/vapor separator cup from the typical factory service illustration. Detailed internal labyrinth is unverified.',[0,.08,.10],364,7],
 ['pump','Electric in-tank fuel pump','Sealed pump can, inlet and outlet. Internal motor and pumping element remain grouped.',[.12,0,0],364,3],['strainer','Fuel-pump inlet strainer','Flattened mesh inlet sock and its locating collar.',[.10,-.13,0],364,4],
 ['coupler','Pump outlet rubber coupler','Flexible outlet connection and sound isolation feature.',[.12,.08,0],364,2],['pump-pad','Pump lower sound insulator','Rubber pump-foot support on the sender bracket.',[.12,-.06,0],364,null],
 ['level-body','Fuel-level sender housing','Sender resistance housing and float-arm pivot. Resistance winding and calibration are not specified.',[-.12,0,0],364,5],['float-arm','Fuel-level float arm','Bent metal float arm, separated from the pivot for inspection.',[-.20,.05,0],364,5],['float','Fuel-level float','Sealed float with rounded ends.',[-.26,.05,.07],364,5],['wires','Pump and sender internal leads','Two terminal leads and ground connection. Connector keying and exact wire colors require direct confirmation.',[.15,0,.12],364,null],
])add('sender-'+key,'fuel-sender',name,description,spread,page,callout);
for(const [key,name,desc,spread,callout] of [
 ['cap','Fuel-filler cap','Factory-style threaded cap with a molded grip and separate seal.',[.18,.12,0],1],['seal','Fuel-cap seal','Annular cap-to-neck seal.',[.12,.09,0],1],['neck','Fuel-filler pipe & vent branch','Formed filler neck from the driver quarter to the early tank. Original bends and clearances remain provisional.',[.14,.04,0],45],['plate','Filler attachment plate','Panel attachment plate behind the fuel pocket.',[.22,0,0],2],['insulator','Filler-neck body insulator','Molded isolator where the neck meets the body pocket.',[.25,0,0],5],['hose','Tank filler coupling hose','Short filler coupling between the pipe and tank.',[0,0,.16],44],['vent-hose','Tank filler vent hose','Separate small vent connection alongside the filler coupling.',[0,.1,.17],44],['clamps','Filler and vent clamps','Separate larger filler and smaller vent clamps.',[.09,0,.22],42],['ground','Filler-pipe ground strap','Bonding strap and attachment eye on the filler pipe.',[.26,-.12,0],45],
])add('filler-'+key,'fuel-filler',name,desc,spread,79,callout);
for(const [key,name,desc,spread,callout] of [
 ['feed','Tank fuel-feed pipe','Separate steel feed route from the sender to the filter inlet connection.',[-.12,0,0],22],['return','Tank fuel-return pipe','Independent return route to the sender.',[.12,0,0],38],['feed-hose','V6 fuel-feed hose & pipe','Formed pipe with flexible section beyond the filter, distinct from the return.',[-.2,.12,0],30],['return-hose','V6 fuel-return hose & pipe','Return pipe and flexible connection at the engine.',[.2,.12,0],33],['couplers','Feed and return hose couplers','Separate short flexible couplers at the tank pipes.',[0,.13,0],21],['clamps','Fuel-hose clamp set','Attachment clamps at the early hose couplers.',[0,.22,0],20],['filter','AC-style in-line fuel filter','Rolled metal filter can with distinct inlet/outlet fittings. Sealed internal media remain grouped.',[-.14,0,.15],28],['filter-bracket','Fuel-filter clamp & bracket','Formed clamp around the cylindrical fuel filter.',[-.25,0,.15],27],['seals','Fuel-filter pipe O-ring pair','Separate seals at the threaded filter connections.',[-.14,.10,.15],26],['pipe-clips','Feed and return pipe clips','Grouped pipe support clips along the reconstructed route.',[0,-.13,0],39],['shield','Fuel-pipe shield','Formed shield at the rear pipe support.',[.12,-.1,.1],34],['fasteners','Fuel-pipe bracket fasteners','Grouped bracket and clip attachment hardware.',[.12,-.2,.1],25],
])add('line-'+key,'fuel-plumbing',name,desc,spread,79,callout);
for(const [key,name,desc,spread,callout,page] of [
 ['canister','Fuel-vapor charcoal canister','Molded cylindrical canister with valve ports and a separate lower air filter. Charcoal bed and valve calibration remain grouped.',[.12,.05,0],72,115],['filter','Vapor-canister lower filter','Porous lower filter pad, a separate service part.',[.12,-.14,0],null,115],['bracket','Vapor-canister support','Split steel support ring and mounting tangs.',[.22,0,0],73,115],['vapor-pipe','Tank-to-canister vapor pipe','Separate vapor route to the driver-side canister; not a duplicate of the high-pressure fuel feed.',[.10,0,.15],77,115],['vapor-hose','Canister vapor hose','Short vapor-pipe connection at the canister port.',[.1,.15,0],70,115],['purge','Canister purge hose pair','Purge and control connections to the engine, reconstructed from the V6 emissions drawing.',[.14,.18,.1],67,115],['clips','Vapor hose and pipe clips','Separate retaining clips and clamps.',[.20,.1,.17],71,115],['relay','Fuel-pump relay','Rectangular relay with mounting ear and downward connector socket. The A/C relay is a separate option.',[-.12,.16,0],7,115],['relay-bracket','Fuel-pump relay bracket','Body attachment bracket for the pump relay.',[-.2,.16,0],7,115],['relay-connector','Fuel-pump relay connector','Keyed plug and short harness branch. No unverified pinout is published.',[-.12,.02,0],7,115],
])add('vapor-'+key,'fuel-vapor',name,desc,spread,page,callout);
