import {wiringParts,wiringSections} from './wiring-catalog.js';
import {chargingParts,chargingSections} from './charging-catalog.js';
import {lightingParts,lightingSections} from './lighting-catalog.js';
import {headlightParts,headlightSections} from './headlight-catalog.js';
import {hvacParts,hvacSections} from './hvac-catalog.js';
import {bodyParts,bodySections} from './body-catalog.js';
import {exhaustParts,exhaustSections} from './exhaust-catalog.js';
import {engineParts,engineSections} from './engine-catalog.js';
import {transmissionParts,transmissionSections} from './transmission-catalog.js';
import {coolingParts,coolingSections} from './cooling-catalog.js';
import {brakeParts,brakeSections} from './brake-catalog.js';
import {suspensionParts,suspensionSections} from './suspension-catalog.js';
import {fuelParts,fuelSections} from './fuel-catalog.js';
export const detailFamilies={
 'wiring-system':{id:'wiring-system',name:'Wiring & controls',shortName:'Instruments / fuses / ECM',system:'electrical',icon:'bolt',kicker:'1985 / ELECTRICAL DISTRIBUTION',coverage:'Original 1985 cluster with separate dials, pointers, pod/lens, center gauges, lower tach oil scale and ten indicator/bulb pairs. Numbered fuse panel and ratings checked against the 1985 owner’s manual; separate fuse elements, sockets, hinge and releases, rear-console ECM enclosure/calibration carriers and 24/32-cavity plugs, battery junction/grounds and distinct turn/hazard flashers. Whole loom circuits, instrument internals, horn units, exact connector tooling, circuit boards and wire lengths remain incomplete. These are static construction views.'},
 'charging-system':{id:'charging-system',name:'Starting / charging',shortName:'Battery / starter / generator',system:'electrical',icon:'bolt',kicker:'1985 / L44 ELECTRICAL',coverage:'Side-terminal battery with heat shield and hold-down; Delco starter, solenoid and drive construction; early generator cast frames, rotor/stator, regulator/rectifier, brushes, bearings and bracket. Original unit stamping/rating, measured castings, exact windings, cable routes, belt interfaces and electrical diagnostics remain to verify.'},
 'lighting-system':{id:'lighting-system',name:'Lighting',shortName:'Exterior / cabin lamps',system:'electrical',icon:'bolt',kicker:'1985 / INCANDESCENT LAMPS',coverage:'Separate front park/turn lamps, four side markers, early notchback rear lamp layers and bulb chambers, license lamps, four overhead reading/dome lamps, manual ashtray lamps and optional courtesy/compartment lighting. Shared native geometry replaces former surface proxies. Exact optical tooling, dimensions, circuit routing, detailed instrument lighting and seal profiles remain unverified.'},
 'headlight-system':{id:'headlight-system',name:'Headlights',shortName:'1985 headlights',system:'electrical',icon:'bolt',kicker:'1985 / EARLY RELAY SYSTEM',coverage:'Separate LH/RH sealed beams, retaining and aiming hardware, buckets, spring-loaded covers, pivots and links, early motors with gear/cushion/brush/contact construction, two actuator relays and driver-side isolation relay with nested coils, armatures, contacts, diodes, open connector shells and 16 individually selectable blades. Separate white/green/gray motor conductors, blue disconnect branches and front-harness C/D fusible links. Raised and closed endpoint poses preserve the low exterior profile. Exact dimensions, optical tooling, gear ratios, measured switch geometry, complete harness circuits and linkage travel remain unverified. Sealed-lamp and riveted-motor separation illustrates construction.'},
 'hvac-system':{id:'hvac-system',name:'HVAC',shortName:'Heating / ventilation',system:'cooling',icon:'water',kicker:'1985 / C41 & C60 PREVIEWS',coverage:'Heater case, option-specific core and controls, air doors, blower cage/motor/resistor, open distribution ducts and C60 evaporator/accumulator/electric actuators. Configure air conditioning to switch C41 and C60 previews; the VIN does not identify this option. Full A/C compressor/condenser detail, circuit wiring, actuator and motor internals, measured housings and clearance/travel validation remain incomplete. Adjacent-year service diagrams supplement the 1985 catalog applications.'},
 'body-system':{id:'body-system',name:'Body',shortName:'Body panels',system:'body',icon:'layers',kicker:'1985 / SE NOTCHBACK BODY',coverage:'Shared exterior skins, separate rockers/door trim/side glass, hood mechanical stay and release, rear decklid torque rods and latch, door hinge straps/pins/latches, wheelhouse liners and panel retaining sets. Revised exterior includes independent mirrors, handles, moldings, bumper pads, fuel door, intake, antenna, wiper arms/blades, roof glass and spoiler previews, plus separate AD3 hinge tongues/bushings, rear release housing/button, trim frames and air deflector. Exact panel sections, body datums, attachment coordinates, mechanism travel, option-specific torque rods, window regulators and detailed locks remain incomplete. This is a static construction explorer, not a body-alignment or repair procedure.'},
 'exhaust-system':{id:'exhaust-system',name:'Exhaust',shortName:'V6 exhaust',system:'fuel',icon:'gear',kicker:'1985 / L44 EXHAUST',coverage:'Manifolds, crossover and shields, spring-loaded downpipe joint, early pellet converter cutaway, transverse muffler, twin tailpipes, clamps, shields and spring hangers. Catalogued 1985–86 assemblies are distinguished from later applications. Local bends, exact profiles, clearances, pellet count and muffler internals remain unverified. Welded-part separation illustrates construction, not a removal procedure.'},
 'fuel-system':{id:'fuel-system',name:'Fuel',shortName:'V6 fuel supply',system:'fuel',icon:'gear',kicker:'1985 / L44 FUEL SUPPLY',coverage:'Early tank shells, straps, pump/sender, driver-side filler, filter, distinct feed/return routes, vapor canister and pump relay. Welded shell separation is an illustrative cutaway. Detailed dimensions, factory routing, pump internals and sender calibration remain unverified; the typical 1986 pump drawing is adjacent-year evidence.'},
 'suspension-system':{id:'suspension-system',name:'Suspension',shortName:'Suspension / steering',system:'suspension',icon:'gear',kicker:'1985 / WS6 ARCHITECTURE',coverage:'Separate front shocks and coils, formed control arms, ball joints, bushings, rear strut stacks and toe links, early cradle, 23 mm front stabilizer, manual steering rack and passenger-side damper. Spring rates/codes, tooth counts, local pivot coordinates and exact stamped/cast profiles remain unverified. Hubs and knuckles can be inspected in the Brakes explorer.'},
 engine:{id:'engine',name:'Engine',shortName:'2.8L V6',system:'engine',icon:'engine',kicker:'L44 / 2.8L V6',coverage:'Engine internals, ignition and service hardware, including nine-piece nested hydraulic lifters and separate water-pump construction selections. Measured castings, complete passages, original pump internal variants, routing and some accessory internals remain incomplete.'},
 transmission:{id:'transmission',name:'Transmission',shortName:'Four-speed',system:'drivetrain',icon:'gear',kicker:'FOUR-SPEED / 76 MM',coverage:'Case, gear trains, reverse idler, synchronizers, bearings, differential, selector and clutch. Gear profiles and casting dimensions are reconstructed. Detailed hydraulics, CV joints and mounting hardware remain incomplete.'},
 'cooling-system':{id:'cooling-system',name:'Cooling',shortName:'Coolant circuit',system:'cooling',icon:'water',kicker:'L44 / COOLANT CIRCUIT',coverage:'Radiator, fan, asymmetric inlet and return pipes, recovery bottle and heater circuit preview. Hose bends, fan variant, clearances and local dimensions need further verification. Thermostat and water pump can be opened through the engine service views.'},
 'braking-system':{id:'braking-system',name:'Brakes',shortName:'1985 brakes',system:'brakes',icon:'disc',kicker:'1985 / FOUR-WHEEL DISC',coverage:'Four separate corners, front integral rotor/hubs, rear hub units, calipers and parking actuators, composite master, tandem booster, lines and cables. Nominal rotor dimensions follow the 1985 DIY manual. Casting profiles, detailed fits, hose clearances, rear piston clutch internals and valve calibration remain unverified.'},
};
export const detailParts=[...wiringParts.map(p=>({...p,family:'wiring-system'})),...chargingParts.map(p=>({...p,family:'charging-system'})),...lightingParts.map(p=>({...p,family:'lighting-system'})),...headlightParts.map(p=>({...p,family:'headlight-system'})),...hvacParts.map(p=>({...p,family:'hvac-system'})),...bodyParts.map(p=>({...p,family:'body-system'})),...exhaustParts.map(p=>({...p,family:'exhaust-system'})),...fuelParts.map(p=>({...p,family:'fuel-system'})),...suspensionParts.map(p=>({...p,family:'suspension-system'})),...engineParts.map(p=>({...p,family:'engine'})),...transmissionParts.map(p=>({...p,family:'transmission'})),...coolingParts.map(p=>({...p,family:'cooling-system'})),...brakeParts.map(p=>({...p,family:'braking-system'}))];
export const detailSections=[...wiringSections.map(p=>({...p,family:'wiring-system'})),...chargingSections.map(p=>({...p,family:'charging-system'})),...lightingSections.map(p=>({...p,family:'lighting-system'})),...headlightSections.map(p=>({...p,family:'headlight-system'})),...hvacSections.map(p=>({...p,family:'hvac-system'})),...bodySections.map(s=>({...s,family:'body-system'})),...exhaustSections.map(s=>({...s,family:'exhaust-system'})),...fuelSections.map(s=>({...s,family:'fuel-system'})),...suspensionSections.map(s=>({...s,family:'suspension-system'})),...engineSections.map(s=>({...s,family:'engine',parent:s.id==='engine'?undefined:s.parent||'engine'})),...transmissionSections.map(s=>({...s,family:'transmission'})),...coolingSections.map(s=>({...s,family:'cooling-system'})),...brakeSections.map(s=>({...s,family:'braking-system'}))];
export const detailPartById=new Map(detailParts.map(p=>[p.id,p]));
export const detailSectionById=new Map(detailSections.map(s=>[s.id,s]));
export const familyFor=section=>detailFamilies[detailSectionById.get(section)?.family||'engine'];
export function inDetailSection(part,section){if(!part)return false;let id=part.section;while(id){if(id===section)return true;id=detailSectionById.get(id)?.parent;}return false;}
export const detailMembers=section=>detailParts.filter(p=>inDetailSection(p,section));

export const detailAvailable=(part,configuration)=>!part?.option||(part.values?part.values.includes(configuration?.[part.option]):configuration?.[part.option]===part.value);
