import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {createInteriorDetail} from './interior-detail.js';
import {interiorParts,interiorSections} from './interior-catalog.js';
import {interiorColor} from './interior-surfaces.js';
import {defaultConfiguration} from './configuration.js';
const host=document.querySelector('#model'),renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(1);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;host.append(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#d4d6d2');scene.add(new T.HemisphereLight('#fff9f0','#717780',1.4));const key=new T.DirectionalLight('#fff5e8',2.0);key.position.set(-2,4,-3);scene.add(key);const fill=new T.DirectionalLight('#e7efff',1);fill.position.set(3,2,3);scene.add(fill);
const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.06).texture;scene.environmentIntensity=.45;room.dispose();pmrem.dispose();
const {root,groups}=createInteriorDetail();scene.add(root);const camera=new T.PerspectiveCamera(35,1,.015,25),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;
const byId=new Map(interiorParts.map(p=>[p.id,p])),config={...defaultConfiguration,roof:'glass',powerWindows:true,mapPockets:true};let current='cabin';
const views={cabin:{name:'Complete cabin',position:[-2.35,1.8,.25],target:[0,.62,.05]},dashboard:{name:'Dashboard from the seats',filter:p=>['interior-dashboard','interior-radio'].includes(p.section)||['in-console-front','in-console-face','in-shared-heater','in-shared-center-outlet'].includes(p.id),position:[.1,1.00,1.65],target:[0,.73,-.48]},seats:{name:'Both seats',filter:p=>p.section.includes('seat-'),position:[-1.15,1.06,-1.42],target:[0,.65,.15]},driver:{name:'Driver seat',section:'interior-seat-left',position:[-1.2,1.07,-.95],target:[-.383,.66,.18]},seatSide:{name:'Seat side profile',section:'interior-seat-left',position:[-2.4,.66,.1],target:[-.383,.66,.15]},seatBack:{name:'Seat rear',section:'interior-seat-left',position:[-.9,1.0,1.6],target:[-.383,.65,.25]},console:{name:'Console and shifter',filter:p=>p.section==='interior-console'||p.section==='interior-radio',position:[-.95,1.26,1.22],target:[0,.55,.02]},door:{name:'Driver door panel',section:'interior-door-left',position:[1.30,.77,-.16],target:[-.72,.54,0]},trim:{name:'Carpet and upper trim',section:'interior-trim',position:[-1.5,1.9,-1.2],target:[0,.74,.02]},steering:{name:'Steering wheel',section:'interior-steering',position:[-.5,.96,.75],target:[-.345,.70,-.21]},pedals:{name:'Pedals and parking brake',section:'interior-pedals',position:[-1,.55,.36],target:[-.38,.39,-.35]}};
const upper=p=>p.id.includes('headliner')||p.id.includes('pillar')||p.id.includes('visor')||p.id==='in-shared-dome';
function render(){renderer.render(scene,camera);}
function update(){const v=views[current],exploded=document.querySelector('#explode').checked,canopy=document.querySelector('#canopy').checked;
 for(const [id,g]of groups){const p=byId.get(id);g.visible=(!(current==='cabin'&&document.querySelector('#cutaway').checked&&p.section==='interior-door-left'))&&(!v.section||p.section===v.section)&&(!v.filter||v.filter(p))&&((current!=='cabin')||canopy||!upper(p));g.position.copy(exploded?g.userData.spread:new T.Vector3());if(exploded&&current==='cabin')g.position.add(g.userData.assemblySpread);
  g.traverse(m=>{if(!m.isMesh)return;const {option,value,materialName}=m.userData;m.visible=!option||config[option]===value;const color=interiorColor(materialName,config);if(color)m.material.color.set(color);if(m.material.transmission){m.material.transmission=0;m.material.transparent=true;m.material.opacity=.09;m.material.depthWrite=false;}});
 }
 root.updateMatrixWorld(true);render();}
function view(name){current=name;const v=views[name];camera.position.set(...v.position);controls.target.set(...v.target);if(document.querySelector('#explode').checked){const target=controls.target.clone();camera.position.sub(target).multiplyScalar(1.5).add(target);}controls.update();update();}
function resize(){renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();render();}
for(const [key,v]of Object.entries(views)){const o=document.createElement('option');o.value=key;o.textContent=v.name;document.querySelector('#view').append(o);}
document.querySelector('#view').onchange=e=>view(e.target.value);document.querySelector('#explode').onchange=()=>view(current);document.querySelector('#canopy').onchange=update;document.querySelector('#cutaway').onchange=update;document.querySelector('#trim').onchange=e=>{config.interior=e.target.value;update();};controls.addEventListener('change',render);new ResizeObserver(resize).observe(host);
const refs={factory:'/references/1985-interior-brochure-i1.png','seat-photo':'/references/1985-se-seat-photo-i1.jpg','seat-parts':'/references/gm-seat-components-i1.png','console-parts':'/references/gm-console-components-i1.png'};for(const [id,url]of Object.entries(refs))document.getElementById(id).onclick=()=>document.querySelector('#reference').src=url;document.getElementById('factory').click();
window.__interiorReview={groups,view,render,visible:()=>[...groups].filter(([id,g])=>g.visible).map(([id])=>id)};resize();view('cabin');renderer.domElement.dataset.ready='true';
