export const suspensionSource='https://fieroinfo.com/manuals/84-88_Fiero_Parts_%26_Illustrations_CD.pdf';
export const suspensionCorners=[{id:'fl',name:'Left front',sign:1,front:true,z:-1.1865},{id:'fr',name:'Right front',sign:-1,front:true,z:-1.1865},{id:'rl',name:'Left rear',sign:1,front:false,z:1.1865},{id:'rr',name:'Right rear',sign:-1,front:false,z:1.1865}];
export const suspensionSections=[
 {id:'suspension-system',name:'Suspension & manual steering'},
 {id:'susp-front',parent:'suspension-system',name:'Front suspension'},
 {id:'susp-rear',parent:'suspension-system',name:'Rear suspension'},
 {id:'susp-rack',parent:'suspension-system',name:'Manual rack, tie rods & damper',spread:[0,.12,-.4]},
 {id:'susp-stabilizer',parent:'susp-front',name:'23 mm front stabilizer & links',spread:[0,-.10,-.24]},
 {id:'susp-crossmember',parent:'susp-front',name:'Front crossmember & mounts',spread:[0,-.18,0]},
 {id:'susp-cradle',parent:'susp-rear',name:'Rear cradle & isolation mounts',spread:[0,-.2,0]},
];
for(const c of suspensionCorners){const id='susp-'+c.id;suspensionSections.push({id,parent:c.front?'susp-front':'susp-rear',name:c.name+' suspension'},
 {id:id+'-arms',parent:id,name:c.name+(c.front?' arms & ball joints':' arm & ball joint'),spread:[c.sign*.2,-.06,0]},
 {id:id+'-spring',parent:id,name:c.name+(c.front?' spring & separate shock':' strut & spring'),spread:[c.sign*.30,.12,0]});
 if(!c.front)suspensionSections.push({id:id+'-toe',parent:id,name:c.name+' toe link',spread:[c.sign*.16,0,.2]});}
export const suspensionParts=[];
function add(id,section,name,description,spread,page,callout,extra={}){suspensionParts.push({id:'su-'+id,section,system:'suspension',name,description,spread,callout,source:'GM 22P · '+(page===193?'1984–87 front suspension':page===219?'1984–87 rear suspension':'manual rack and pinion'),sourceUrl:suspensionSource+'#page='+page,location:suspensionSections.find(s=>s.id===section).name,referenceNote:'Factory illustration and application table establish component identity. Local dimensions, loaded spring shape, casting/stamping contours, fits and finishes are reconstructed. Exact WS6 spring codes and rates require the car’s RPO/build information. This view is not a repair sequence.',...extra});}
for(const c of suspensionCorners){
 const part=(key,name,section,description,spread,callout)=>add(c.id+'-'+key,'susp-'+c.id+'-'+section,c.name+' '+name,description,[spread[0]*c.sign,spread[1],spread[2]],c.front?193:219,callout,{corner:c.id,role:key});
 const arms=c.front?['upper','lower']:['lower'];
 for(const level of arms){const up=level==='upper',cy=up?.16:-.16;
  part(level+'-arm',level+' control arm','arms','Formed steel arm with an open center, rolled edges, bushing eyes and ball-joint seat. The 1985–87 front lower-arm application is retained.',[0,cy,0],c.front?up?7:17:c.sign===1?32:22);
  for(const [key,name,spread,callout] of [
   ['bush-front','front pivot bushing',[.06,cy,-.16],c.front?up?49:24:null],['bush-rear','rear pivot bushing',[.06,cy,.16],c.front?up?9:24:null],
   ['pivot-bolts','pivot bolt set',[-.07,cy,.22],c.front?up?31:33:19],['pivot-washers','pivot washer set',[-.07,cy,.28],c.front?up?30:32:20],
   ['pivot-nuts','pivot nuts / retainers',[-.07,cy,-.23],c.front?up?10:26:21],
   ['joint','ball-joint housing',[.15,cy-.08,0],c.front?up?8:18:null],['stud','ball-joint stud',[.15,cy+.08,0],null],['boot','ball-joint dust boot',[.15,cy+.15,0],null],
   ['joint-fasteners',c.front&&up?'ball-joint factory rivet set':'ball-joint retaining hardware',[.24,cy-.08,0],c.front?up?8:18:33],
   ['joint-nut','ball-joint retaining nut',[.15,cy+.21,0],c.front?up?13:16:34],['cotter',c.front?'ball-joint cotter pin':'ball-joint clamp hardware',[.20,cy+.25,0],c.front?14:null],
  ])part(level+'-'+key,level+' '+name,'arms','Separate '+name+' in the '+level+' arm. Ball-joint interior surfaces are illustrative; this does not imply the sealed joint is intended to be rebuilt.',spread,callout);
 }
 if(c.front){
  for(const [key,name,spread,callout] of [['spring','coil spring',[0,.28,0],27],['isolator','upper spring insulator',[0,.38,0],28],['shock-body','shock body',[.16,0,.12],11],['shock-rod','shock rod & cover',[.16,.20,.12],11],['shock-lower-bush','shock lower eye bushing',[.22,-.10,.12],11],['shock-upper-bush','shock upper eye bushing',[.22,.26,.12],11],['shock-bolts','shock mounting bolts',[.28,.1,.12],12],['shock-nuts','shock mounting nuts',[.34,.1,.12],16],['bumpstop','lower-arm jounce bumper',[-.08,.12,.1],23]])part(key,name,'spring','Separate '+name+'. The front shock is mounted outside the coil spring. Installed dimensions and WS6 calibration are provisional.',spread,callout);
 }else{
  for(const [key,name,y,callout] of [['strut-body','strut damper body',-.18,11],['strut-rod','strut piston rod',.04,11],['lower-seat','lower spring seat',-.10,11],['lower-isolator','lower spring insulator',-.04,12],['spring','coil spring',.10,10],['dust-boot','strut dust shield',.22,9],['jounce','strut jounce bumper',.30,8],['upper-isolator','upper spring insulator',.38,7],['upper-seat','upper spring seat',.45,5],['seat-washer','spring-seat washer',.51,6],['mount','rubber strut mount',.58,4],['mount-washer','strut shaft upper washer',.66,3],['shaft-nut','strut shaft nut',.72,2],['reinforcement','upper mount reinforcement plate',.80,1],['mount-washers','body-mount washer set',.87,53],['mount-nuts','body-mount nut set',.92,54],['knuckle-bolts','strut-to-knuckle bolt pair',-.14,13],['knuckle-washers','knuckle bolt washers',-.20,14],['knuckle-nuts','knuckle bolt nuts',-.26,15]])part(key,name,'spring','Separate '+name+' from the early rear-strut stack. Internal hydraulic valves are not exposed as verified components.',[key.startsWith('knuckle')?.26:0,y,0],callout);
  for(const [key,name,x,callout] of [['toe-inner','inner toe link',-.06,45],['toe-inner-joint','inner toe-link pivot',-.12,45],['toe-boot','inner toe-link seal',-.2,47],['toe-clamps','inner toe-link clamps',-.26,46],['toe-outer','outer toe-link end',.08,43],['toe-seal','outer toe-link seal',.16,40],['toe-jam','toe adjustment jam nut',.23,44],['toe-nut','toe ball-stud nut',.30,39],['toe-cotter','toe stud cotter pin',.35,41],['toe-attachment','inner toe-link attachment',-.32,28]])part(key,name,'toe','Separate '+name+'; the rear toe link is distinct from the steering rack’s front tie rods. Exact rod lengths and ball-joint details are reconstructed.',[x,0,0],callout);
 }
}
for(const [key,name,spread,callout] of [
 ['bar','Front stabilizer bar',[0,0,-.12],2],['bushings','Stabilizer mounting insulators',[0,.12,0],1],['clamps','Stabilizer mounting clamps',[0,.22,0],40],['bolts','Stabilizer clamp bolts',[0,.29,0],41],
])add('stab-'+key,'susp-stabilizer',name,'Early front anti-roll bar and frame attachment. The factory catalog identifies a 23 mm bar; local bends and bushing dimensions are reconstructed.',spread,193,callout,{role:key});
for(const [side,s] of [['left',1],['right',-1]])for(const [key,name,spread,callout] of [['bolt','end-link bolt',[s*.12,-.14,0],19],['spacer','end-link spacer',[s*.12,.05,0],29],['grommets','end-link rubber grommets',[s*.12,.17,0],5],['washers','end-link cupped washers',[s*.12,.27,0],4],['nut','end-link nut',[s*.12,.34,0],6]])add('stab-'+side+'-'+key,'susp-stabilizer',side[0].toUpperCase()+side.slice(1)+' stabilizer '+name,'Individually selectable '+name+' at the front control arm.',spread,193,callout,{role:key,side});
suspensionParts.find(p=>p.id==='su-stab-bar').serviceReference={title:'Factory front stabilizer reference',rows:[['Catalog shaft diameter','23 mm']],note:'GM 22P front-suspension application table, callout 2. This verifies the nominal shaft diameter, not the reconstructed bends, spring rates or complete WS6 option inventory.',links:[['GM 22P · front suspension table',suspensionSource+'#page=194']]};
for(const [key,name,spread,callout] of [
 ['housing','Manual rack housing',[0,0,0],1],['rack','Steering rack bar',[-.55,0,0],29],['pinion','WS6 pinion & shaft',[0,.25,0],3],['bearing','Pinion roller bearing',[0,.15,0],2],['seal','Pinion shaft seal',[0,.33,0],5],['ring','Pinion retaining ring',[0,.38,0],4],['bushing','Passenger-end rack bushing',[-.22,0,0],33],['bushing-ring','Rack-bushing retaining ring',[-.28,0,0],32],['guide','Rack support bearing',[0,0,.12],9],['spring','Rack adjuster spring',[0,0,.19],8],['plug','Rack adjustment plug',[0,0,.25],7],['locknut','Rack adjuster locknut',[0,0,.31],6],['mounts','Rack mounting grommets',[0,-.14,0],31],['clamps','Rack mounting brackets',[0,-.24,0],30],['bolts','Rack mounting bolts',[0,-.32,0],null],['damper','Steering damper assembly',[0,0,-.26],28],['adapter','Passenger tie-rod damper adapter',[-.16,0,-.16],21],['boot-support','Passenger boot support',[-.12,0,0],24],['damper-studs','Steering damper mounting studs',[0,0,-.12],25],['damper-washers','Steering damper washers',[0,0,-.34],27],['damper-nuts','Steering damper nuts',[0,0,-.4],26],
])add('rack-'+key,'susp-rack',name,key==='pinion'?'The catalog distinguishes 1985 WS6 from non-WS6 pinions. Tooth count, ratio and exact geometry remain unverified; this is a visual reconstruction.':'Separate '+name+' in the original manual steering architecture. No hydraulic power-steering components are introduced.',spread,197,callout,{role:key});
for(const [side,s] of [['left',1],['right',-1]])for(const [key,name,x,y,callout] of [['inner','inner tie rod',.14,0,11],['outer','outer tie-rod end',.28,0,15],['boot','rack bellows',.20,.14,s===1?13:23],['clamps','bellows clamps',.20,.24,s===1?12:22],['seal','outer tie-rod seal',.30,.12,17],['jam','tie-rod jam nut',.22,.06,14],['nut','tie-rod stud nut',.30,.20,18],['cotter','tie-rod cotter pin',.30,.26,19],['grease','tie-rod lubrication fitting',.30,-.10,16]])add('rack-'+side+'-'+key,'susp-rack',side[0].toUpperCase()+side.slice(1)+' '+name,'Separate '+name+'. The two bellows have distinct placements; the damper and its boot support are on the passenger side.',[s*x,y,0],197,callout,{role:key,side});
for(const [id,section,name,page,items] of [
 ['crossmember','susp-crossmember','Front crossmember',193,[['frame','formed crossmember',34],['braces','diagonal rail braces',45],['upper-bolts','upper rail attachment bolts',44],['lower-bolts','lower brace bolts',48],['washers','rail attachment washers',43],['shock-brackets','upper shock brackets',null]]],
 ['cradle','susp-cradle','Rear cradle',219,[['frame','formed cradle frame',27],['front-bushings','front isolation bushings',23],['front-bolts','front attachment bolts',24],['upper-cushions','rear upper isolation cushions',49],['lower-cushions','rear lower isolation cushions',26],['spacers','rear cushion spacers',50],['retainers','rear cushion retainers',25],['rear-bolts','rear attachment bolts',25],['captive-nuts','rear captive nuts & retainers',51]]],
])for(const [i,[key,label,callout]] of items.entries())add(id+'-'+key,section,name+' '+label,'Separate '+label+'. Frame contours and mounting coordinates follow factory illustration relationships and require measured confirmation.',[0,key==='frame'?0:(i%2?1:-1)*(.08+i*.035),0],page,callout,{role:key});
