import {mvma1985,m17Nominal} from './factory-specifications.js';
// Component identity follows GM 22P's 1985–86 MY8/M17 plate. Numbered
// callouts below deliberately use the separately linked 1986 service plate.
export const transmissionSource='https://fieroinfo.com/manuals/1986_Fiero_Service_Manual.pdf';
export const transmissionPartsSource='https://fieroinfo.com/manuals/84-88_Fiero_Parts_%26_Illustrations_CD.pdf';
export const transmissionSections=[
 {id:'transmission',name:'Complete four-speed transaxle'},
 {id:'trans-case',parent:'transmission',name:'Case, covers & seals',spread:[.35,0,0]},
 {id:'trans-input',parent:'transmission',name:'Input shaft & 3rd / 4th synchro',spread:[0,.20,-.17]},
 {id:'trans-output',parent:'transmission',name:'Output shaft & 1st / 2nd synchro',spread:[0,.06,.19]},
 {id:'trans-reverse',parent:'transmission',name:'Reverse idler',spread:[0,-.12,-.19]},
 {id:'trans-differential',parent:'transmission',name:'Final drive & differential',spread:[0,-.22,.20]},
 {id:'trans-selector',parent:'transmission',name:'Shift rails, forks & detent',spread:[0,.37,0]},
 {id:'trans-clutch',parent:'transmission',name:'Flywheel, clutch & release',spread:[-.27,0,0]},
];
export const transmissionParts=[];
const add=(id,section,name,callout,spread=[0,0,0],description='')=>transmissionParts.push({id:'tx-'+id,section:'trans-'+section,system:'drivetrain',name,callout,spread,location:transmissionSections.find(s=>s.id==='trans-'+section).name,source:'Pontiac service manual · 7B1-2 / 7B1-3',sourceUrl:transmissionSource+'#page=802',description:description||`${name} in the GM four-speed exploded drawing. Separate native 3D geometry; local profiles and dimensions are reconstructed.`,referenceNote:'1985–86 application: GM 22P MY8/M17 plate, PDF 128–130. Callout numbers here refer to the adjacent-year 1986 service drawing. Tooth counts, helix angles, fits and tolerances are illustrative; this is not a manufacturing model or disassembly sequence.'});
for(const row of [
 ['case','Case assembly',1,[.28,.06,0]],['bellhousing','Clutch & differential housing',46,[-.28,0,0]],['vent','Case vent',2,[.28,.20,0]],['magnet','Oil-debris magnet',3,[.30,-.13,0]],['dowels','Case locating dowels',4,[.18,.02,.10]],['drain-washer','Drain screw washer',5,[.18,-.17,0]],['drain','Drain screw',6,[.18,-.22,0]],['case-bolts','Case bolt set',7,[.41,.06,0]],['fill-washer','Fill plug washer',8,[.23,0,.15]],['fill','Fill plug',9,[.23,0,.21]],['axle-seals','Axle oil seal pair',10,[.40,0,.08]],['case-plug','Case gallery plug',11,[.24,.04,-.13]],['input-seal','Input shaft seal',37,[-.16,0,0]],['input-retainer','Input bearing retainer & guide',38,[-.10,0,0]],['retainer-seal','Input retainer seal ring',40,[-.05,0,0]],['retainer-screws','Input retainer screws',35,[-.22,0,0]],['speed-retainer','Speed sensor retainer & screw',48,[0,.24,.05]],['speed-sensor','Vehicle speed sensor body',49,[0,.17,.05]],['speed-seal','Speed sensor O-ring',50,[0,.11,.05]],['speed-gear','Speedometer driven gear',51,[0,.06,.05]],
])add(row[0],'case',...row.slice(1));
add('input-shaft','input','Clutch input cluster shaft',33,[0,0,0],'Splined clutch-input end, stepped journals and integral low-ratio gear cluster. The input and output axes are spaced 76 mm in this reconstruction.');
for(const row of [['input-bearing','Input front bearing',34,[-.04,0,0]],['input-end-bearing','Input end bearing',13,[.14,0,0]],['input-shim','Input bearing adjustment shim',36,[-.085,0,0]],['input-shield','Input bearing oil shield',12,[.18,0,0]],['input-sleeve','Input shaft oil-shield sleeve',24,[.22,0,0]],['third-input','Third-speed input gear',32,[-.06,.055,0]],['fourth-input','Fourth-speed input gear',30,[.10,.055,0]],['sync34','Third / fourth synchronizer hub & sleeve',31,[.04,.12,0]],['block3','Third-speed blocking ring',18,[-.045,.095,0]],['block4','Fourth-speed blocking ring',18,[.11,.095,0]],['keys34','Third / fourth synchronizer keys',21,[.025,.17,0]],['springs34','Third / fourth key retaining springs',20,[.025,.21,0]],['retainer34','Third / fourth retaining ring',19,[.07,.15,0]]])add(row[0],'input',...row.slice(1));
add('output-shaft','output','Output shaft & final-drive pinion',25,[0,0,0]);
for(const row of [['first-output','First-speed output gear',23,[-.10,0,.06]],['second-output','Second-speed output gear',17,[.01,0,.08]],['third-output','Third-speed output gear',16,[.09,0,.05]],['fourth-output','Fourth-speed output gear',14,[.16,0,.045]],['sync12','First / second synchronizer hub & sleeve',22,[-.045,0,.14]],['block1','First-speed blocking ring',18,[-.11,0,.11]],['block2','Second-speed blocking ring',18,[.015,0,.12]],['keys12','First / second synchronizer keys',21,[-.045,0,.19]],['springs12','First / second key retaining springs',20,[-.045,0,.23]],['retainer12','First / second retaining rings',19,[-.045,0,.27]],['third-retainer','Third-speed output retaining ring',15,[.10,0,.10]],['output-bearing','Output front bearing',26,[-.14,0,0]],['output-shim','Output bearing adjustment shim',27,[-.19,0,0]],['output-shield','Output bearing oil shield',28,[-.23,0,0]],['output-retainer','Output shield retainer',29,[-.27,0,0]],['output-end-bearing','Output end bearing',13,[.23,0,0]],['output-end-shield','Output end bearing oil shield',12,[.28,0,0]],['output-sleeve','Output shaft oil-shield sleeve',24,[.32,0,0]]])add(row[0],'output',...row.slice(1));
for(const row of [['reverse-shaft','Reverse idler shaft',43,[0,0,0]],['reverse-gear','Reverse idler gear',44,[.06,-.10,0]],['reverse-spacer','Reverse idler spacer',45,[.12,0,0]],['reverse-bolt','Reverse shaft screw & washer',42,[-.08,0,0]]])add(row[0],'reverse',...row.slice(1));
for(const row of [['diff-carrier','Differential carrier',77,[0,0,0]],['ring-gear','Final-drive ring gear',87,[.17,0,0]],['ring-bolts','Ring gear bolts',88,[.25,0,0]],['diff-bearings','Differential bearing pair',76,[.13,0,.09]],['diff-shim','Differential bearing shim',80,[.18,0,.13]],['speed-drive','Speedometer drive gear',79,[-.14,0,0]],['diff-pin','Differential pinion shaft',78,[0,.13,0]],['diff-pin-screw','Pinion shaft retaining screw',86,[0,.21,0]],['diff-pin-washer','Pinion retaining lockwasher',85,[0,.17,0]],['spider-gears','Differential pinion gear pair',82,[0,.10,.10]],['spider-washers','Pinion thrust washer pair',81,[0,.17,.14]],['side-gears','Differential side gear pair',84,[.085,0,.12]],['side-washers','Side gear thrust washer pair',83,[.13,0,.17]]])add(row[0],'differential',...row.slice(1));
for(const row of [['fork34','Third / fourth shift fork',68,[.05,.09,0]],['fork12','First / second shift fork',72,[-.045,.09,0]],['fork-rail','Shift fork rail',69,[0,.16,0]],['shift-shaft','External shift shaft',61,[.04,.23,0]],['shift-seal','Shift shaft seal',62,[.12,.24,0]],['detent-lever','Detent lever',57,[0,.22,-.06]],['detent-spring','Detent spring',59,[0,.29,-.06]],['detent-bolt','Detent lever bolt & lockwasher',60,[0,.36,-.06]],['interlock','Shift interlock',65,[.02,.18,.05]],['shift-shim','Shift shaft shim',66,[.05,.25,.05]],['reverse-lever','Reverse shift lever',55,[.06,.08,-.08]],['reverse-stud','Reverse lever locating stud',56,[.06,.16,-.10]],['inhibitor','Reverse inhibitor spring, seat & washer',53,[.08,.27,-.1]],['roll-pins','Shift mechanism roll pins',54,[.13,.30,0]],['rail-screw','Shift rail screw',70,[.19,.16,0]],['oil-guide','Gear oil guide',71,[.16,.18,.07]]])add(row[0],'selector',...row.slice(1));
for(const row of [['flywheel','Manual-engine flywheel & ring gear',3,[-.24,0,0]],['disc','Sprung clutch driven plate',2,[-.14,0,0]],['pressure','Pressure plate & cover',1,[-.06,0,0]],['release-bearing','Clutch release bearing',6,[.04,0,0]],['cover-bolts','Clutch cover bolts & lockwashers',8,[.02,.08,0]],['flywheel-bolts','Flywheel bolt set',5,[-.30,0,0]],['release-fork','Clutch release fork & shaft',75,[.06,.10,0]],['fork-bearings','Clutch fork shaft bearings',74,[.06,.17,0]],['fork-seal','Clutch fork shaft seal',73,[.06,.24,0]]]){
 add(row[0],'clutch',...row.slice(1));const p=transmissionParts.at(-1);if(!row[0].startsWith('fork')&&row[0]!=='release-fork'){p.source='GM 22P · clutch cover & plate';p.sourceUrl=transmissionPartsSource+'#page=40';p.referenceNote='The 1985–86 V6 driven plate is distinguished from the later five-speed application in this factory table. Springs, facing slots and local dimensions are reconstructed.';}
}

for(const key of ['tx-output-shaft','tx-ring-gear'])Object.assign(transmissionParts.find(p=>p.id===key),{serviceReference:{title:'1985 L44 / M17 final drive',rows:[['Final-drive pinion','23 teeth'],['Final-drive ring gear','84 teeth'],['Nominal ratio','3.65:1 (84/23)']],links:[['Pontiac 1985 final-drive specification',mvma1985+'#page=11']],note:'Factory tooth counts are applied to the model. Tooth profiles, helix angles, pitch diameters and running mesh remain reconstructed.'}});
Object.assign(transmissionParts.find(p=>p.id==='tx-disc'),{serviceReference:{title:'1985 L44 four-speed clutch facing',rows:[['Outside diameter','232.0 mm'],['Inside diameter','155.0 mm'],['Factory facing reference','14087220']],links:[['Pontiac 1985 clutch specification',mvma1985+'#page=10']],note:'These nominal facing diameters are applied to the model. Carrier form, spring pockets, rivet pattern, slots and pressure-plate casting remain reconstructed.'}});

for(const key of ['tx-output-shaft','tx-ring-gear'])transmissionParts.find(p=>p.id===key).referenceNote='Final-drive tooth counts follow Pontiac 1985 MVMA printed9: pinion23, ring84. Profiles, helix, pitch dimensions and the other speed-gear tooth counts remain reconstructed. This is not manufacturing geometry.';
